### ISSUE TITLE
Add initialDelaySeconds to livinessProbe or enable configurable thresholds

### ISSUE THREAD

**Issue by alekskar** [bank-vaults/bank-vaults#1028]
**Is your feature request related to a problem? Please describe.**
Vault has backends for AWS like dynamo and s3. However to use them you should provide credentials. AWS support 2 solutions to eliminate this. IAM roles for Service Accounts and Instance profile roles. 
Due to some unknown reason vault requires more time to start when using dynamic creds than explicit definition keys in s3 block or credentialsConfig.
initialDelaySeconds: x tels the kubelet that it should wait x seconds before first probe
Currently these values are hardcoded:
``` 
          livenessProbe:
            httpGet:
              path: /v1/sys/init
              port: api-port
              scheme: HTTPS
            timeoutSeconds: 1
            periodSeconds: ${configurable} 10 sec by default
            initialDelaySeconds: ${configurable} 45  <------------- suggestion 
            successThreshold: 1
            failureThreshold: 3
```
**Describe the solution you'd like**
It would be great to have all  3 parameters configurable in the current vault custom resource:
```
vaultChecks:
   livenessPeriodSeconds: 10
   readinessPeriodSeconds: 5
   initialDelaySeconds: 30
```
**Describe alternatives you've considered**
as an alternative I suggest just  to add `initialDelaySeconds` :
```
          livenessProbe:
            httpGet:
              path: /v1/sys/init
              port: api-port
              scheme: HTTPS
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            **initialDelaySeconds: 45**
```

**Comment by Tolsto** [comment]
Ran into the same issue. DynamoDB storage backend with IAM role bindings to service accounts.

**Comment by bonifaido** [comment]
No doubt this is needed, and we are open for PRs for this one (as always)! 🙂

**Comment by Ninja-mann** [comment]
thank you! you rock bro!

**Comment by CodeGlitcher** [comment]
we are also running into this issue.
Our vault pod is killed before it has even logd it is starting (our test server is juist running the bare min hardware)

I was looking add the code, but go is not my favorite langue.
I dont understand how to make it complete configurable but juist to add some better defaults all it would need is to add:
PeriodSeconds:    10,
FailureThreshold: 3,
InitialDelaySeconds: 60,
TimeoutSeconds: 1
to the vault_controller.go for the LivenessProbe & ReadinessProbe objects.
Would that be possible?

**Comment by Rasek91** [comment]
Hello @CodeGlitcher, you can `vaultPodSpec` or `vaultContainerSpec` in the Vualt CRD to change the LivenessProbe & ReadinessProbe:
```yaml
  vaultContainerSpec:
    livenessProbe:
      httpGet:
        path: /v1/sys/init
        port: api-port
        scheme: HTTPS
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
      failureThreshold: 3
      initialDelaySeconds: 60
```

**Comment by CodeGlitcher** [comment]
Thats not a valid solution...

We dont make manally changes to what we deploy on k8s.
We want everything we deploy on k8s in git.

The use of helm chars and operators prevent the need to have a copy of every applications yamls file and manually keep them up to data.

**Comment by 9digitdev** [comment]
If we can't find a way to update the readiness probe for vault this will be deal killer for us. Is there a way to set default values in the CRD to allow us to get past this blocker?

**Comment by akijakya** [comment]
Hi, for me this config worked:

```yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
...
  vaultContainerSpec:
    name: "vault"
    livenessProbe:
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
      failureThreshold: 3
      initialDelaySeconds: 60
...
```

Result:

```json
kubectl get po vault-0 -o jsonpath={".spec.containers[0].livenessProbe"} | jq
{
  "failureThreshold": 3,
  "httpGet": {
    "path": "/v1/sys/init",
    "port": "api-port",
    "scheme": "HTTPS"
  },
  "initialDelaySeconds": 60,
  "periodSeconds": 10,
  "successThreshold": 1,
  "timeoutSeconds": 1
}
```
