### ISSUE TITLE
End2end guide for Vault Go Client within Kubernetes

### ISSUE THREAD

**Issue by YiannisGkoufas** [bank-vaults/bank-vaults#1133]
Was going through the go example https://github.com/banzaicloud/bank-vaults/blob/master/cmd/examples/main.go and was wondering if there is a guide about running this go example within k8s, ideally accessing the vault instance provisioned by the operator.

This guide https://banzaicloud.com/blog/vault-operator/#local-vault-operator was very helpful to install it locally and worked out the box. Just wondering about ways of using your vault go client within a k8s pod in the same cluster.

Great stuff by the way.

**Comment by bonifaido** [comment]
Hi @YiannisGkoufas, there is no general guide TBH, but we use the client across the whole code base, so there are plenty of other examples as well. But I will leave this issue open to document the client more properly here: https://banzaicloud.com/docs/bank-vaults/go-library/

**Comment by YiannisGkoufas** [comment]
Thanks @bonifaido can I ask just for few directions? Like I can see this:
```
client, err := vault.NewClientFromConfig(
		config,
		vault.ClientAuthPath(vaultPath),
		vault.ClientLogger(logrusadapter.New(logrus.New())),
	)
```
What would shoud I be aware of when creating a pod for this to work (regarding service accounts, secrets etc)

**Comment by bonifaido** [comment]
The serviceAccount of the pod has to be authorized to access Vault and the secrets in Vault. Like configured here with the operator: https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr.yaml#L133
```yaml
    auth:
      - type: kubernetes
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: ["default", "vault-secrets-webhook", "vault"]
            bound_service_account_namespaces: ["default", "vswh"]
            policies: ["allow_secrets", "allow_pki"]
            ttl: 1h
```
