### ISSUE TITLE
Pod not initializing with consul-template

### ISSUE THREAD

**Issue by mikeyGlitz** [bank-vaults/bank-vaults#1212]
I've tried to instantiate a Deployment using the following yaml:

```yaml
 apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config-template
  namespace: linkerd
data:
  config.hcl: |
    vault {
      ssl {
        ca_cert = "/vault/tls/ca.crt"
      }
      retry {
        backoff = "1s"
      }
    }
    template {
      contents = <<EOH
        {{ with secret "secret/keycloak/monitoring-proxy/credential" }}
        client_id = "{{ .Data.data.client_id }}"
        client_secret = "{{ .Data.data.client_secret }}"
        {{ end }}
        cookie_secret = "{{ .Data.data.encryption_key }}"
        http_address = ":3000"
        upstreams = [ "http://linkerd-web.linkerd.svc.cluster.local:8084/" ]
        redirct_url = "https://monitoring.haus.net"
        provider = "keycloak"
        login_url = "https://auth.haus.net/realms/hausnet/protocol/openid-connect/auth"
        redeem_url ="https://auth.haus.net/realms/hausnet/protocol/openid-connect/token"
        validate_url = "https://auth.haus.net/realms/hausnet/protocol/openid-connect/userinfo"
      EOH
      destination = "/vault/secrets/oauth2-config.cfg"
      command = "/bin/sh -c \"kill -HUP $(pidof oauth2-proxy) || true\""
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-web-proxy
  namespace: linkerd
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    matchLabels:
      app: linkerd-web-proxy
  template:
    metadata:
      labels:
        app: linkerd-web-proxy
      annotations:
        vault.security.banzaicloud.io/vault-ct-configmap: proxy-config-template
        vault.security.banzaicloud.io/vault-addr: https://vault.vault-system:8200
        vault.security.banzaicloud.io/vault-tls-secret: vault-cert-tls
        vault.security.banzaicloud.io/vault-role: default
    spec:
      containers:
      - name: linkerd-web-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy
        ports:
        - containerPort: 3000
        args:
          - --config="/vault/secrets/oauth2-config.cfg"
---
```

When the pod initializes, it fails the healtcheck. The logs indicate the following

consul-template
```
Loading...
sh: you need to specify whom to kill
```

oauth2-proxy
```
[error] unable to read the configuration file: "/vault/secrets/oauth2-config.cfg", error: open "/vault/secrets/oauth2-config.cfg": no such file or directory
```

When I run the `kubectl exec` command I can see that the file is present

```
kubectl exec -it -n linkerd linkerd-web-proxy-6ddf9c44c5-ch4jb -- ls /vault/secrets
Defaulting container name to consul-template.
Use 'kubectl describe pod/linkerd-web-proxy-6ddf9c44c5-ch4jb -n linkerd' to see all of the containers in this pod.
gatekeeper.yaml
```

How do I fix this problem? Did I do something wrong with my configuration?
