### ISSUE TITLE
[mutating webhook] Vault-Agent has an error at startup - OCP 4.7 - OpenShift

### ISSUE THREAD

**Issue by dawidek88** [bank-vaults/bank-vaults#1277]
**Describe the bug**:
When you want to use the vault agent to insert secrets from the vault into an application (container)

Vault-agent starts with an error  on openshift 4.7
The /vault/logs directory missed
```
stat: can't stat '/vault/logs': No such file or directory
chown: /vault/logs: No such file or directory
```

In the app pod yaml file with the vault agent I see the args with
```
        args:
        - agent
        - '-config'
        - /vault/config/config.hcl
```
and a snippet from the pod
```
 securityContext:
    seLinuxOptions:
      level: 's0:c28,c27'
    supplementalGroups:
      - 1000810000
    fsGroup: 1000810000
  containers:
    - resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      terminationMessagePath: /dev/termination-log
      name: vault-agent
      env:
        - name: VAULT_ADDR
          value: 'https://vault.cao-vault:8200'
        - name: VAULT_SKIP_VERIFY
          value: 'false'
        - name: VAULT_CACERT
          value: /vault/tls/ca.crt
      securityContext:
        capabilities:
          add:
            - SYS_PTRACE
            - IPC_LOCK
        allowPrivilegeEscalation: false
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: vault-env
          mountPath: /vault/
        - name: vault-tls
          mountPath: /vault/tls/
        - name: vault-test-token-hpsmk
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        - name: agent-secrets
          mountPath: /vault/secrets
        - name: agent-configmap
          readOnly: true
          mountPath: /vault/config/config.hcl
          subPath: config.hcl
      terminationMessagePolicy: File
      image: 'vault:1.6.2'
      args:
        - agent
        - '-config'
        - /vault/config/config.hcl
    - resources: {}
      terminationMessagePath: /dev/termination-log
      name: alpine
      command:
        - sh
        - '-c'
        - echo going to sleep... && sleep infinity
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
          drop:
            - ALL
        runAsUser: 101
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: vault-test-token-hpsmk
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        - name: agent-secrets
          mountPath: /vault/secrets
      terminationMessagePolicy: File
      image: 'mtr.external.otc.telekomcloud.com/cao/alpine:3.13.2'
  serviceAccount: vault-test
  volumes:
    - name: vault-test-token-hpsmk
      secret:
        secretName: vault-test-token-hpsmk
        defaultMode: 420
    - name: vault-env
      emptyDir:
        medium: Memory
    - name: vault-tls
      projected:
        sources:
          - secret:
              name: vault-tls
              items:
                - key: ca.crt
                  path: ca.crt
        defaultMode: 420
    - name: agent-secrets
      emptyDir:
        medium: Memory
    - name: agent-configmap
      configMap:
        name: myapp
        items:
          - key: config.hcl
            path: config.hcl
        defaultMode: 420
  dnsPolicy: ClusterFirst
```
Then I have been created my own pod and changed the command to:
```
        command: [vault]
        args:
        - agent
        - '-config'
        - /vault/config/config.hcl
```
Then the pod will be started without an error. But that was only a test.

I noticed that the volume is not mounted (/vault/logs) on the agent:
![image](https://user-images.githubusercontent.com/41817216/111614236-a4f66500-87df-11eb-80aa-9ed68099cc11.png)

I'm not sure but maybe this is the part where the volume mount (/vault/logs) for the agent needs to add:
https://github.com/banzaicloud/bank-vaults/blob/master/cmd/vault-secrets-webhook/pod.go#L499

**Expected behaviour**:
vault-agent starts without an error and inject with the correct config templates the secrets into the app container

**Steps to reproduce the bug**:
Values and cr files to reproduce the error for vault-agent: 

VAULT_CR:
```
# Source: vault-server/templates/vault-cr.yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: vault-server
  labels:
    app.kubernetes.io/name: vault-server
    vault_cr: vault
spec:
  size: 3
  image: vault:1.6.2

  # Common annotations for all created resources
  annotations:
    common/annotation: "true"

  # Vault Pods, Services and TLS Secret annotations
  vaultAnnotations:
    type/instance: "vault"

  # Vault Configurer Pods and Services annotations
  vaultConfigurerAnnotations:
    type/instance: "vaultconfigurer"

  # Vault Pods, Services and TLS Secret labels
  vaultLabels:
    example.com/log-format: "json"

  # Vault Configurer Pods and Services labels
  vaultConfigurerLabels:
    example.com/log-format: "string"

  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: "vault-server"

  # Specify the Service's type where the Vault Service is exposed
  # Please note that some Ingress controllers like https://github.com/kubernetes/ingress-gce
  # forces you to expose your Service on a NodePort
  serviceType: ClusterIP

 # Use local disk to store Vault raft data, see config section.
  volumeClaimTemplates:
    - metadata:
        name: vault-raft
      spec:
        # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
        # storageClassName: ""
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 10Gi

  volumeMounts:
    - name: vault-raft
      mountPath: /vault/file

  # Add Velero fsfreeze sidecar container and supporting hook annotations to Vault Pods:
  # https://velero.io/docs/v1.2.0/hooks/
  veleroEnabled: false

  # Support for distributing the generated CA certificate Secret to other namespaces.
  # Define a list of namespaces or use ["*"] for all namespaces.
  caNamespaces:
    - "cao-vault"
    - "vault"
  #  - "vswh"

  # Describe where you would like to store the Vault unseal keys and root token.
  unsealConfig:
    options:
      # The preFlightChecks flag enables unseal and root token storage tests
      # This is true by default
      preFlightChecks: true
    kubernetes:
      secretNamespace: cao-vault

  # A YAML representation of a final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    storage:
      raft:
        path: "/vault/file"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
        
        telemetry: # Needed to use the metrics access with auth token
          unauthenticated_metrics_access: false
    telemetry:
      prometheus_retention_time: "30s"
      disable_hostname: true

    api_addr: https://${.Env.POD_NAME}.cao-vault:8200
    cluster_addr: "https://${.Env.POD_NAME}:8201"
    ui: true

  statsdDisabled: true
  serviceRegistrationEnabled: true

  resources:
    # A YAML representation of resource ResourceRequirements for vault container
    # Detail can reference: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container
    vault:
      limits:
        memory: 512Mi
        cpu: 200m
      requests:
        memory: 256Mi
        cpu: 100m

  # See: https://banzaicloud.com/docs/bank-vaults/cli-tool/#example-external-vault-configuration
  # The repository also contains a lot examples in the deploy/ and operator/deploy directories.
  externalConfig:
    policies: 
    
      - name: prometheus-operator
        rules: path "sys/metrics" {
          capabilities = ["list", "read"]
          }

      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: sudo
        rules: path "*" {
          capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }
    auth:

      # Enable kubernetes auth
      - type: kubernetes
        roles:
            
          - name: prometheus
            bound_service_account_names: ["prometheus-k8s"]
            bound_service_account_namespaces: monitoring
            policies: prometheus-operator
            ttl: 5h
  
          # Custom auth roles for kubernetes  
          - name: "vault-testapp-role"
            bound_service_account_names: ["vault-testapp"]
            bound_service_account_namespaces: ["vault"]
            policies: allow_secrets
            ttl: 1h

      # Enable OIDC auth
      - type: oidc
        config:
            # Add needed variables for config
            oidc_client_id: "vault-client"
            oidc_client_secret: "xxx"
            default_role: "oidc-sso" 
            oidc_discovery_url: "https://keycloak.xxx/auth/realms/CAO"
        roles:
          # Add role for OIDC-SSO
          - name: "oidc-sso"
            bound_audiences: "vault-client"
            allowed_redirect_uris: ["https://vault.xxx/ui/vault/auth/oidc/oidc/callback", "https://vault.xxx/oidc/callback"]
            user_claim: "sub"
            policies: "sudo"

    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2

  
    # Allows writing some secrets to Vault (useful for development purposes).
    # See https://www.vaultproject.io/docs/secrets/kv/index.html for more information.
    startupSecrets:
      - type: kv
        path: secret/data/accounts/aws
        data:
          data:
            AWS_ACCESS_KEY_ID: secretId
            AWS_SECRET_ACCESS_KEY: s3cr3t
      - type: kv
        path: secret/data/dockerrepo
        data:
          data:
            DOCKER_REPO_USER: dockerrepouser
            DOCKER_REPO_PASSWORD: dockerrepopassword
      - type: kv
        path: secret/data/mysql
        data:
          data:
            MYSQL_ROOT_PASSWORD: s3cr3t2


  # vaultEnvsConfig:
  #   - name: VAULT_LOG_LEVEL
  #     value: info
```
MUTATING_WEBHOOK_VALUES:
```
# Default values for vault-secrets-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

nameOverride: vault-mutating-webhook
fullnameOverride: ""

debug: true

certificate:
  useCertManager: false
  servingCertificate: null
  generate: true
  server:
    tls:
      crt:
      key:
  ca:
    crt:
  extraAltNames: []
  # use extra names if you want use the webhook via an ingress or a loadbalancer

image:
  repository: ghcr.io/banzaicloud/vault-secrets-webhook
  pullPolicy: Always
  imagePullSecrets: []
  tag: "1.11.2"

service:
  name: vault-secrets-webhook
  type: ClusterIP
  externalPort: 443
  internalPort: 8443
  annotations: {}
  # Annotate service
  # This can be used for example if type is AWS LoadBalancer and you want to add security groups

ingress:
  enabled: false
  annotations: {}
  # dns of ingress for vault-webhook
  # host: example.com

webhookClientConfig:
  # By default the mutating webhook uses the service of the webhook directly to contact webhook
  # Use url if webhook should be contacted over loadbalancer or ingress instead of service object
  useUrl: false
  # set the url how the webhook should be contacted (including protocol https://)
  # url: https://example.com

vaultEnv:
  repository: ghcr.io/banzaicloud/vault-env

vaultServer:
  helmReleaseName: vault-server

cluster:
  # Option if you want to deploy the webhook on the same or other cluster
  same: true
  different: false

env:
  VAULT_IMAGE: vault:1.6.2
  # VAULT_CAPATH: /vault/tls
  # # Used when the pod that should get secret injected does not
  # # specify an imagePullSecret
  # DEFAULT_IMAGE_PULL_SECRET:
  # DEFAULT_IMAGE_PULL_SECRET_NAMESPACE:
  # VAULT_CLIENT_TIMEOUT: 10s
  # # define the webhook's role in Vault used for authentication,
  # # if not defined individually in resources by annotations.
  # VAULT_ROLE: vault-secrets-webhook
  # VAULT_ADDR: https://vault-server.vault:8200
  VAULT_SKIP_VERIFY: false
  #VAULT_TLS_SECRET: vault-server-tls

metrics:
  enabled: false
  port: 8443
  serviceMonitor:
    enabled: false
    scheme: https
    tlsConfig:
      insecureSkipVerify: true

securityContext: 
  runAsNonRoot: true
  # runAsUser: 65534
  # allowPrivilegeEscalation: false

podSecurityContext: {}

volumes: []
# - name: vault-tls
#   secret:
#     secretName: vault-tls

volumeMounts: []
# - name: vault-tls
#   mountPath: /vault/tls

podAnnotations: {}

labels: {}
  #  team: banzai

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

## Assign a PriorityClassName to pods if set
priorityClassName: ""

rbac:
  psp:
    enabled: false
  authDelegatorRole:
    enabled: false

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Labels to add to the service account
  labels: {}
  # Annotations to add to the service account
  annotations: {}
  # Enables GKE workload identity
  #  iam.gke.io/gcp-service-account: gsa@project.iam.gserviceaccount.com
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# A list of Kubernetes resource types to mutate as well:
# Example: ["ingresses", "servicemonitors"]
customResourceMutations: []

customResourcesFailurePolicy: Ignore

# This can cause issues when used with Helm, so it is not enabled by default
configMapMutation: false

configMapFailurePolicy: Ignore

podsFailurePolicy: Ignore

secretsFailurePolicy: Ignore

apiSideEffectValue: NoneOnDryRun

namespaceSelector:
  matchExpressions:
    - key: name
      operator: NotIn
      values:
        - kube-system
  # matchLabels:
  #   vault-injection: enabled

# In case of the K8s cluster version is above 1.15 objectSelector is usable
objectSelector: {}
  # matchExpressions:
  # - key: security.banzaicloud.io/mutate
  #   operator: NotIn
  #   values:
  #   - skip

podDisruptionBudget:
  enabled: true
  minAvailable: 1

timeoutSeconds: false

hostNetwork: false
```

SCC:
```
# Source: vault-server/templates/scc_ocp.yaml
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: vault-restricted
  annotations:
    kubernetes.io/description: This is the least privileged SCC and it is used by vault users.
allowHostIPC: true
allowHostDirVolumePlugin: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
defaultAddCapabilities: null
allowedCapabilities:
  - "*" 
  # - IPC_LOCK
  # - SETFCAP
allowedUnsafeSysctls: null
fsGroup:
  type: RunAsAny
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
  # - KILL
  # - MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
users:
  - system:serviceaccount:cao-vault:vault-server
  - system:serviceaccount:cao-vault:vault-operator
  - system:serviceaccount:cao-vault:vault-mutating-webhook
  # - system:serviceaccount:cao-vault-testapp:vault-testapp-sa
```
VAULT_AGENT_CONFIG_MAP:
```
# Source: vault-testapp/templates/vault-app-vault-agent-secret-test-cm copy.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-testapp
  labels:
    helm.sh/chart: vault-testapp-0.1.0
    app.kubernetes.io/name: vault-testapp
    app.kubernetes.io/instance: vault-testapp
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  config.hcl: |
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "vault-testapp-role"
        }
      }
      sink "file" {
        config = {
          path = "/vault/.vault-token"
        }
      }
    }
    template {
      contents = <<EOH
      {{- with secret "secret/data/accounts/aws" }}
      test: {{ .Data.data.AWS_ACCESS_KEY_ID }}{{- end -}}
      EOH
      destination = "/vault/secrets/test.txt"
    }

    template { 
      contents = <<EOH
      {{ with secret "secret/data/accounts/aws" }}
      value1: {{ .Data.data.AWS_ACCESS_KEY_ID }}
      value2: {{ .Data.data.AWS_ACCESS_KEY_ID }}
      {{ end }}
      EOH
      destination = "/vault/secrets/test2.txt"
    }

    # template { 
    #   contents = <<EOH
    #   {{ with secret "secret/data/truststore" }}
    #   {{ base64Decode .Data.data.keystore }}
    #   {{ end }}
    #   EOH
    #   destination = "/vault/secrets/truststore"
    # }"
```

APP_VAULT_AGENT:
```
# Source: vault-testapp/templates/vault-app-vault-agent-secret-test.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-testapp-vault-agent
  labels:
    helm.sh/chart: vault-testapp-0.1.0
    app.kubernetes.io/name: vault-testapp
    app.kubernetes.io/instance: vault-testapp
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-testapp
      app.kubernetes.io/instance: vault-testapp
  template:
    metadata:
      annotations:
        #vault.security.banzaicloud.io/vault-tls-secret: vault-server-tls
        #vault.security.banzaicloud.io/vault-agent: "true" # optional, if true, a Vault Agent will be started to do Vault authentication, by default not needed and vault-env will do Kubernetes Service Account based Vault authentication
        vault.security.banzaicloud.io/vault-agent-configmap: vault-testapp
      labels:
        app.kubernetes.io/name: vault-testapp
        app.kubernetes.io/instance: vault-testapp
    spec:
      serviceAccountName: vault-testapp
      containers:
      - name: vault-testapp
        image: alpine:3.13.2
        command: ["sh", "-c", "echo going to sleep... && sleep infinity" ]
```

**Environment details**:
- OpenShift version: 4.7 stable
- Kubernetes version: v1.20.0+ba45583
- Vault-Server version: 1.6.2
- bank-vaults version 1.11.2
- Install method helm (operator): chart 1.11.3

/kind bug

**Comment by jb-elos** [comment]
Hi guys,
we are experiencing the same issue but under different conditions (because I beleive it is same issue, I'm posting to existing issue and not creating new one).
We are running the same versions of comoponents as described in issue definition.
We are running vault auto-unseal transit setup.
In this setup tenant Vault instance will not start up correctly a ends in CrashLoopBackOff condition.

The exact same error appers in vault container.
```
$ oc logs pod/vault-tenant-0 -c vault
time="2021-04-26T14:34:25Z" level=info msg="received new Vault token" app=vault-env
time="2021-04-26T14:34:25Z" level=info msg="initial Vault token arrived" app=vault-env
time="2021-04-26T14:34:25Z" level=info msg="spawning process: [docker-entrypoint.sh server]" app=vault-env
stat: can't stat '/vault/logs': No such file or directory
chown: /vault/logs: No such file or directory
```

Here is final definition of vault tenant pod after mutated by webhook:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: vault-webhook-mutated
    vault.banzaicloud.io/tls-expiration-date: "2022-04-26T14:13:11Z"
    vault.security.banzaicloud.io/vault-addr: https://vault-central.vault-central:8200
    vault.security.banzaicloud.io/vault-path: tenant/kubernetes
    vault.security.banzaicloud.io/vault-role: tenant
    vault.security.banzaicloud.io/vault-tls-secret: vault-central-tls
  name: vault-tenant-0
...
spec:
  automountServiceAccountToken: true
  containers:
  - args:
    - docker-entrypoint.sh
    - server
    command:
    - /vault/vault-env
    env:
    - name: VAULT_K8S_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: VAULT_TOKEN
      value: vault:login
    - name: VAULT_ADDR
      value: https://vault-central.vault-central:8200
    - name: VAULT_SKIP_VERIFY
      value: "false"
    - name: VAULT_AUTH_METHOD
      value: jwt
    - name: VAULT_PATH
      value: tenant/kubernetes
    - name: VAULT_ROLE
      value: tenant
    - name: VAULT_IGNORE_MISSING_SECRETS
      value: "false"
    - name: VAULT_ENV_PASSTHROUGH
    - name: VAULT_JSON_LOG
      value: "false"
    - name: VAULT_CLIENT_TIMEOUT
      value: 10s
    - name: VAULT_LOG_LEVEL
      value: debug
    - name: VAULT_CACERT
      value: /vault-env/tls/ca.crt
    image: vault:1.6.2
    name: vault
    ports:
    - containerPort: 8200
      name: api-port
      protocol: TCP
    - containerPort: 8201
      name: cluster-port
      protocol: TCP
    securityContext:
      capabilities:
        add:
        - IPC_LOCK
        - SETFCAP
    volumeMounts:
    - mountPath: /vault-central/tls
      name: vault-central-tls
    - mountPath: /vault/config
      name: vault-config
    - mountPath: /vault/file
      name: vault-file
    - mountPath: /vault/tls
      name: vault-tls
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: vault-token-xpqcp
      readOnly: true
    - mountPath: /vault/
      name: vault-env
    - mountPath: /vault-env/tls/
      name: vault-env-tls
  - args:
    - --pre-flight-checks
    - "true"
    - --mode
    - k8s
    - --k8s-secret-namespace
    - vault-tenant
    - --k8s-secret-name
    - vault-tenant-unseal-keys
    - --k8s-secret-labels
    - app.kubernetes.io/name=vault,vault_cr=vault-tenant
    command:
    - bank-vaults
    - unseal
    - --init
    - --auto
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: VAULT_ADDR
      value: https://127.0.0.1:8200
    - name: VAULT_CACERT
      value: /vault/tls/ca.crt
    image: banzaicloud/bank-vaults:1.11.3
    imagePullPolicy: IfNotPresent
    name: bank-vaults
    ports:
    - containerPort: 9091
      name: metrics
      protocol: TCP
    volumeMounts:
    - mountPath: /vault/tls
      name: vault-tls
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: vault-token-xpqcp
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: vault-tenant-0
  initContainers:
  - command:
    - sh
    - -c
    - cp /usr/local/bin/vault-env /vault/
    image: banzaicloud/vault-env:1.11.3
    imagePullPolicy: IfNotPresent
    name: copy-vault-env
    securityContext:
      allowPrivilegeEscalation: false
    volumeMounts:
    - mountPath: /vault/
      name: vault-env
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: vault-token-xpqcp
      readOnly: true
  - args:
    - template
    - -file
    - /vault/config/vault.json
    command:
    - /vault/vault-env
    env:
    - name: VAULT_LOCAL_CONFIG
      value: '{"api_addr":"https://vault-tenant.vault-tenant:8200","listener":{"tcp":{"address":"0.0.0.0:8200","tls_cert_file":"/vault/tls/server.crt","tls_key_file":"/vault/tls/server.key"}},"seal":{"transit":{"address":"https://vault-central.vault-central:8200","key_name":"autounseal","mount_path":"tenant/transit","tls_ca_cert":"/vault-central/tls/ca.crt"}},"storage":{"file":{"path":"/vault/file"}},"ui":true}'
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: VAULT_TOKEN
      value: vault:login
    - name: VAULT_ADDR
      value: https://vault-central.vault-central:8200
    - name: VAULT_SKIP_VERIFY
      value: "false"
    - name: VAULT_AUTH_METHOD
      value: jwt
    - name: VAULT_PATH
      value: tenant/kubernetes
    - name: VAULT_ROLE
      value: tenant
    - name: VAULT_IGNORE_MISSING_SECRETS
      value: "false"
    - name: VAULT_ENV_PASSTHROUGH
    - name: VAULT_JSON_LOG
      value: "false"
    - name: VAULT_CLIENT_TIMEOUT
      value: 10s
    - name: VAULT_LOG_LEVEL
      value: debug
    - name: VAULT_CACERT
      value: /vault-env/tls/ca.crt
    image: banzaicloud/bank-vaults:1.11.3
    imagePullPolicy: IfNotPresent
    name: config-templating
    volumeMounts:
    - mountPath: /vault-central/tls
      name: vault-central-tls
    - mountPath: /vault/config
      name: vault-config
    - mountPath: /vault/file
      name: vault-file
    - mountPath: /vault/tls
      name: vault-tls
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: vault-token-xpqcp
      readOnly: true
    - mountPath: /vault/
      name: vault-env
    - mountPath: /vault-env/tls/
      name: vault-env-tls
  preemptionPolicy: PreemptLowerPriority
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000
    seLinuxOptions:
      level: s0:c29,c4
    supplementalGroups:
    - 1000
  serviceAccount: vault
  serviceAccountName: vault
  volumes:
  - name: vault-central-tls
    secret:
      defaultMode: 420
      secretName: vault-central-tls
  - emptyDir:
      medium: Memory
      sizeLimit: 1Mi
    name: vault-config
  - name: vault-file
    persistentVolumeClaim:
      claimName: vault-file
  - name: vault-tls
    secret:
      defaultMode: 420
      secretName: vault-tenant-tls
  - name: vault-token-xpqcp
    secret:
      defaultMode: 420
      secretName: vault-token-xpqcp
  - emptyDir:
      medium: Memory
    name: vault-env
  - name: vault-env-tls
    projected:
      defaultMode: 420
      sources:
      - secret:
          items:
          - key: ca.crt
            path: ca.crt
          name: vault-central-tls
```

I spend on this problem already almost one week.
We are really stuck there.
I tried many and many configurations.
I don't know exact internal processes of vault operator and vault secrets webhook, so I'm not able to debug it more and find out where the problem is. So my approach was mainly "trial and error".
I can say (based on my knowledge and testing) that operator is working, central vault instance is working - teste auth and so on, mutating of pods by webhook is working - I can see json patch for mutated pod in debug log.
But there is definitely something wrong with the resulting pod, because of the error.
If any one can help me and instruct me where is a problem a what I could try to solve this I would be very happy.
Thanks in advance for any hint.

**Comment by pbalogh-sa** [comment]
Hello. The /vault/logs directory shouldn't be mounted. It is a local directory if you don't set `fluentdEnabled` flag.  Please check whether some of the SELinux contexts prevent the `/vault/logs` directory creation.

**Comment by jb-elos** [comment]
Hi and thanks for quick response.

I'm curiouse why this problem does not happen when I start standalone Vault instance - there is also /vault/logs directory an it is working correctly.
But when it is Vault tenant instance, the pod is mutated by webhook, than it will not start.

I managed to start the debug pod. It cannot be started as is, because the mutating webhook will mutate the debug pod also and it will create duplicated entries in pod spec and the pod will not start.
So I have to create the vault-tenant instance and when the vault-tenant pod is in crashloopbackoff condition, then I have to delete mutatingwebhookconfiguration. Then I successfully started the debug pod.

There is really no /vault/logs directory.
But when the vault is created by operator without mutation (regular Vault instance - not tenant), then there is /vault/logs directory. When the directory should be created? The entrypoint is awaiting the directory already, but is missing.

Here is the output what can be observerd in debug pod before entrypoint start:
```
$ oc debug pod/vault-test-0
Defaulting container name to vault.
Use 'oc describe pod/vault-test-0-debug -n vault-tenant' to see all of the containers in this pod.

Starting pod/vault-test-0-debug, command was: /vault/vault-env docker-entrypoint.sh server
Pod IP: 10.16.2.237
If you don't see a command prompt, try pressing enter.
/ #
/ # id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video),1000(vault)
/ #
/ # ls -al /vault
total 35156
drwxrwsrwt 5 root vault 120 Apr 27 14:59 .
dr-xr-xr-x 1 root root 78 Apr 27 14:59 ..
drwxrwsrwt 2 root vault 60 Apr 27 14:59 config
drwxrwsr-x 3 root vault 4096 Apr 27 14:39 file
drwxrwsrwt 3 root vault 160 Apr 27 14:59 tls
-rwxr-xr-x 1 nobody vault 35991724 Apr 27 14:59 vault-env
/ #
/ # ls -al /vault/config/
total 4
drwxrwsrwt 2 root vault 60 Apr 27 14:59 .
drwxrwsrwt 5 root vault 120 Apr 27 14:59 ..
-rw------- 1 nobody vault 398 Apr 27 14:59 vault.json
/ #
/ # /vault/vault-env docker-entrypoint.sh server
INFO[0000] received new Vault token app=vault-env
INFO[0000] initial Vault token arrived app=vault-env
INFO[0000] spawning process: [docker-entrypoint.sh server] app=vault-env
stat: can't stat '/vault/logs': No such file or directory
chown: /vault/logs: No such file or directory
```

It could be, that the mutating webhook will add another volume to the pod.
The volume is volume-env and it is mounted under /vault mountpoint.
So it will hide the original structure.
```
    volumeMounts:
    - mountPath: /vault-central/tls
      name: vault-central-tls
    - mountPath: /vault/config
      name: vault-config
    - mountPath: /vault/file
      name: vault-file
    - mountPath: /vault/tls
      name: vault-tls
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: vault-token-xpqcp
      readOnly: true
    - mountPath: /vault/
      name: vault-env
    - mountPath: /vault-env/tls/
      name: vault-env-tls
```
The last two volumes are added by mutating webhook.

Maybe the mounting is done in incorrect order (I don't know if it is possible to specify mount order)
Or subPath should be used.
Or mount vault-env under different mount path, for example /vault-env.

Is it possible to check that? And if this is true, is it possible to change the mutating point deffiniton and correct the mounting?

There could be possible some workaround, for example create /vault/logs directory after mutation, so then it should be in the vault-env binary probably which is the entrypoint which is copied from init container and the init container is added by mutating webhook .

But probably the correction of mountPath vault-env volume is better option.

The error looks like comes from docker-entrypoint.sh 
https://github.com/hashicorp/vault/blob/64c04a7439006b5169a8122128773c45a6062a06/scripts/docker/docker-entrypoint.sh#L78

Not sure why the directory is important, because Vault in container is not using that directory by default - vault logs to stdout.
But when I start vault server in debug pod it will start the vault itself and dont get error message.
