### ISSUE TITLE
vault agent templates for the init containers

### ISSUE THREAD

**Issue by dzirg44** [bank-vaults/bank-vaults#1290]
**Is your feature request related to a problem? Please describe.**
Hi. As I discovered vault agent doesn't modify  'init containers' , it can be useful in applications where we have DB migrations.  

**Describe the solution you'd like**
maybe something like this
```yaml
        vault.security.banzaicloud.io/vault-addr: "https://vault.default:8200"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
        vault.security.banzaicloud.io/vault-role: "dev"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-agent-configmap: vault-agent-pki
       vault.security.banzaicloud.io/vault-init-agent-configmap: vault-agent-pki
```
of course I would like to have rendered secrets  via  agent only in certain containers , but I don't know how to achieve it.

**Describe alternatives you've considered**
I made a custom chart where I have one short lived init container, where I get token, and another init container where I use it token via consul-template. If everything works fine,a deployment will be created as well.
