### ISSUE TITLE
Webhook secrets should not be regenerated at each restart

### ISSUE THREAD

**Issue by yelhouti** [bank-vaults/bank-vaults#1326]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
Helm apply of vault-webhook regenerates at each install/update, this causes helm diff to not be empty and therefore helmfile to call helm update.

**Expected behaviour**:
If nothing changes not reinstall

**Steps to reproduce the bug**:
create helmfile wiith:
```
filepath: ""
namespace: vault
repositories:
  - name: banzaicloud-stable
    url: https://kubernetes-charts.banzaicloud.com
releases:
  - chart: banzaicloud-stable/vault-operator
    name: vault-operator
    version: 1.12.0
    wait: true
  - chart: banzaicloud-stable/vault-secrets-webhook
    name: vault-secrets-webhook
    version: 1.12.0
    wait: true 
```

**Additional context**:
Helm 3 introduced a lookup function that allows to retrieve the existing values and reuse them.

/kind bug
