### ISSUE TITLE
Keycloak OIDC group mapping to Vault groups

### ISSUE THREAD

**Issue by maxkokocom** [bank-vaults/bank-vaults#1371]
**Describe the bug**:
I tried many different settings but I am not able to map groups from keycloak to vault groups which I would expect to be the most important function of it. Maybe I am missing something.

**Expected behaviour**:
When I add auth.type: oidc with config it should create connections, policies, groups and mapping.

**Steps to reproduce the bug**:
```yaml
  externalConfig:
    policies:
      - name: team_x_user
        rules:
          path "teams/team_x/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: oidc
        config:
          oidc_discovery_url: "https://keycloak.mydomain.com/auth/realms/master"
          oidc_client_id: "vault"
          oidc_client_secret: "${oidc_secret}"
          default_role: default_user
        roles:
          - name: default_user
            bound_audiences: "vault"
            user_claim: email
            groups_claim: /realm_access/roles # tried also groups, /groups/0/name, and few others, none worked
            role_type: oidc
            allowed_redirect_uris:
              - http://localhost:8250/oidc/callback
              - https://vault.mydomain.com/ui/vault/auth/oidc/oidc/callback
            policies: "default_user"
            claim_mappings: {
              email: email,
              name: name
            }
            oidc_scopes:
              - email
              - groups
            ttl: 1h
    groups:
      - name: team_x
        policies:
          - team_x_user
        metadata:
          team: "team_x"
        type: external
```

**Additional context**:
Everything above does work except for creating groups based on token groups. I tried to create groups myself (groups section above), but they have to be external as internal is not supported yet so even manually I am not able to add Vault users to those. 

I did try multiple values for `groups_claim` field but none seems to work. 

vault-configurer container logs don't have any warnings, it applies other settings from the above config

My JWT token from Vault has a groups section and looks like that:
```json
{
  "exp": xxx,
  "iat": xxx,
  "jti": "xxx",
  "iss": "https://keycloak.mydomain.com/auth/realms/master",
  "aud": "account",
  "sub": "xxx",
  "typ": "Bearer",
  "azp": "vault",
  "session_state": "xxx",
  "acr": "1",
  "allowed-origins": [
    "https://vault.mydomain.com"
  ],
  "realm_access": {
    "roles": [
      "team_x",
      "default-roles-master",
      "offline_access",
      "uma_authorization"
    ]
  },
  "scope": "openid email groups profile",
  "email_verified": false,
  "name": "XXX",
  "groups": [
    "/ArgoCDReadOnly",
    "/team_x"
  ],
  "preferred_username": "XXX",
  "given_name": "XXX",
  "family_name": "XXX",
  "email": "XXX"
}
```

**Environment details**:
- Cloud-provider/provisioner GKE
- Install method: helm chart version 3.0.4

/kind bug

**Comment by anoncam** [comment]
Keycloak helm chart version 3.0.4?  

What version of Vault are you running?

**Comment by anoncam** [comment]
```
groups_claim=‘groups’`
```

setup the role mapper in Keycloak to “groups”
```
vault write identity/group name='test-group' \
        policies='test-policy' \
        type='external'
```
```
vault write identity/group-alias name='{a value from groups_claim}' \
        mount_accessor=auth_oidc_xxxx \
        canonical_id='{id from group creation}'
```

[Reference](https://keycloak.discourse.group/t/keycloak-client-role-mapping-with-vault/4082/3)

**Comment by ksiadz** [comment]
Sorry forgotten vault version, 1.6.2 via vault-bank chart 1.13.1.

Well, the suggested code you are giving me requires an existing mount_accessor which at the point of vault init is not known. Creating a separate automation to provision vault is always an option, but I think the point of this init config is to avoid it.

**Comment by anoncam** [comment]
It might be worth upgrading to Vault 1.7.x -- I think creating that mount_accessor with Terraform is quite manageable and easily automated.  Although to your point it would be preferable to handle on init.  I will think more about this issue.

**Comment by ksiadz** [comment]
Thank you, I will take a look at managing it from tf, but we currently use vault-bank chart fully so we would need to change a lot. Tt would be great if `groups_claim` could handle it. I was thinking it's doing it for other oidc, maybe wrongly.

**Comment by anoncam** [comment]
I need to do some oidc implementations as well with our Vault.  So good timing for me to do more research.

**Comment by joshuasimon-taulia** [comment]
not exactly keycloak, but this works for me with okta
```
    auth:
      - type: oidc
        config:
          oidc_client_id: "${env `OKTA_OIDC_ID`}"
          oidc_client_secret: "${env `OKTA_OIDC_SECRET`}"
          oidc_discovery_url: https://{{ .Values.okta.org }}.okta.com
          default_role: operations
        options:
          listing_visibility: "unauth"
        roles:
          - name: operations
            user_claim: email
            groups_claim: groups
            role_type: oidc
            oidc_scopes:
              - email
              - groups
              - openid
              - profile
            # use for custom okta auth server
            # bound_audiences:
            #   - "${env `OKTA_OIDC_ID`}"
            allowed_redirect_uris:
              - https://{{ $fullName }}.{{ $subdomain }}/ui/vault/auth/oidc/oidc/callback
              - https://localhost:8200/oidc/callback
              - http://localhost:8200/oidc/callback
              - http://localhost:8250/oidc/callback
            policies: admin
            ttl: 20m
            max_ttl: 60m
            num_uses: 0
            {{- if .Values.debugLogging }}
            verbose_oidc_logging: true
            {{- end }}
```
