### ISSUE TITLE
Can not specify what jwt to use when using projected secret

### ISSUE THREAD

**Issue by nomatterz** [bank-vaults/bank-vaults#1376]
**Describe the bug**:
I'm using `vault-secrets-webhook` to fetch secret from external vault.
I've configured `jwt` auth method in Vault.
I have projected secret with token. And if i'm exec'ing into pod i can get Vault token and use it to fetch secrets
```
export JWT=$(cat /var/run/secrets/eks.amazonaws.com/serviceaccount/token)
/ # ./vault write -tls-skip-verify auth/jwt/login role=demo jwt="$JWT"
Key                  Value
---                  -----
token                s.KU8dWtc4ZWF29WFOAzNoLbSi
token_accessor       LX2UWju7R1XLORpk5CxYq78m
token_duration       192h
token_renewable      true
token_policies       ["default" "test"]
identity_policies    []
policies             ["default" "test"]
token_meta_role      demo
```

But webhook is not able to get the Vault token. I suspect that wrong token is provided - `/var/run/secrets/kubernetes.io/serviceaccount/token` instead of `/var/run/secrets/eks.amazonaws.com/serviceaccount/token`

I'm getting 
```
time="2021-07-03T11:13:15Z" level=error msg="failed to request new Vault token" app=vault-env err="Error making API request.\n\nURL: PUT https://vault.vault-infra.svc.cluster.local/v1/auth/jwt/login\nCode: 400. Errors:\n\n* error validating token: error verifying token signature: failed to verify id token signature"
```
and i can not find the way to specify which token webhook should use.

**Expected behaviour**:
I need a way to provide proper JWT to be able to login and get Vault token.

**Steps to reproduce the bug**:
Described above

**Environment details**:
- Kubernetes version (e.g. v1.10.2): `1.18`
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): `EKS`
- bank-vaults version (e.g. 0.4.17): `vault-secrets-webhook only 1.13.0`
- Install method (e.g. helm or static manifests): `helm`
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: temp
  namespace: test-vault
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::myacc:role/test-deleteme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp
  namespace: test-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: temp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: temp
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.vault-infra.svc.cluster.local" # optional, the address of the Vault service, default values is https://vault:8200
        vault.security.banzaicloud.io/vault-role: "demo" # optional, the default value is the name of the ServiceAccount the Pod runs in, in case of Secrets and ConfigMaps it is "default"
        vault.security.banzaicloud.io/vault-skip-verify: "false" # optional, skip TLS verification of the Vault server certificate
        vault.security.banzaicloud.io/vault-tls-secret: "test-vault" # optional, the name of the Secret where the Vault CA cert is, if not defined it is not mounted
        vault.security.banzaicloud.io/vault-agent: "false" # optional, if true, a Vault Agent will be started to do Vault authentication, by default not needed and vault-env will do Kubernetes Service Account based Vault authentication  
        vault.security.banzaicloud.io/vault-path: "jwt"
    spec:
      serviceAccountName: temp
      securityContext:
        fsGroup: 1337
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "echo $TEST && echo going to sleep... && sleep 10000"]
        env:
        - name: TEST
          value: vault:secret/test/test#the_answer
```

/kind bug
