### ISSUE TITLE
Injecting Inline Mutation Secrets Into CRDs Not Working / Documented

### ISSUE THREAD

**Issue by fvosburgh** [bank-vaults/bank-vaults#1387]
**Describe the bug**:
I am currently attempting to leverage bank-vaults to inject a secret into a cert-manager CRD. We want to have our cluster internal Vault populate our AWS credentials in our ClusterIssuer. Our specs look like the following:

CRD
```
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.vault.svc.cluster.local:8200" 
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-skip-verify: "false"
    vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
    vault.security.banzaicloud.io/vault-agent: "false"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
    vault.security.banzaicloud.io/inline-mutation: "true"
spec:
    .
    .
    .
    solvers:
    - dns01:
        route53:
          region: us-east-2
          hostedZoneID: ${vault:secret/data/testing/aws/creds#zone_id}
          accessKeyID: ${vault:secret/data/testing/aws/creds#key_id}
    .
    .
    .
```

vault-cr:
```
.
.
.

externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: ["default", "vault-secrets-webhook", "vault", "cert-manager", "cert-manager-cainjector", "cert-manager-webhook"]
            bound_service_account_namespaces: ["default", "vault", "vswh", "cert-manager"]
            policies: ["allow_secrets", "allow_pki"]
            ttl: 1h
.
.
.
    startupSecrets:
      - type: kv
        path: secret/data/testing/aws/creds
        data:
          data:
            key_id: "XXXXXXX"
            zone_id: "XXXXXXXX"
```

No modifications have been made to the operator or webhook deployments.

The CRD is in the cert-manager namespace, and the cert-manager controller uses the cert-manager service account. I have not seen anything in the webhook or vault logs to indicate that the webhook is even looking at the CRD for mutation.

We also see that the template string gets passed to cert-manager and is not templated out

```
Failed to change Route 53 record set: IncompleteSignature: Credential must
    have exactly 5 slash-delimited elements, e.g. keyid/date/region/service/term,
    got '${vault:secret/data/testing/aws/creds#key_id}/20210721/us-east-1/route53/aws4_request'\n\tstatus
    code: 403, request id: XXXXXXXX"
```

I have tested these annotations and vault format string in a test pod that spits them out as environment variables in the logs and ran into no issues.

I have looked at the bank-vaults documentation, existing issues, and the bank-vaults slack for more information about how to inject secrets into arbitrary objects, but have found nothing aside from this on the documentation [site](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/configuration/#inject-secret-into-resources)

Can someone point me to relevant documentation or help me understand why the webhook is not seeing my CRD?

**Expected behaviour**:
vault-webhook should be injecting secret into ClusterIssuer CRD

**Steps to reproduce the bug**:
- Deploy vault-operator, vault-cr with startup secrets, vault-webhook, and cert-manager to an EKS cluster running k8s 1.19
- Create a ClusterIssuer spec that references the startup secrets in Vault
- Observe that the vault-webhook does not pick up on the ClusterIssuer vault request

**Environment details**:
- EKS running k8s 1.19
- vault-operator chart version 1.13.1
- vault-webhook chart version 1.13.1
- cert-manager chart version 0.16.0

/kind bug

**Comment by EvertonSA** [comment]
I did not know you could use the bank-vaults annotations in CRD's, I'm using for workloads only. Let us know if you succed with this test! One thing I would like to mention, you might give it a shot:

```
      - type: kubernetes
        config:
          kubernetes_host: https://kubernetes.default.svc
          disable_iss_validation: true
        roles:
          - name: default
 ...
```

don't know why my EKS mutate the service account tokens before they are passed into pods (i'm not running 1.21). more info here: https://github.com/banzaicloud/bank-vaults/issues/1346
