### ISSUE TITLE
[operator] Servicemonitor endpoint port doesn't match any vault service port

### ISSUE THREAD

**Issue by forselli-stratio** [bank-vaults/bank-vaults#1424]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
When deploying vault  with serviceMonitorEnabled: true, a servicemonitor is created pointing to a port named "prometheus", but vault service doesn't have a port with that name so it doesn't match.

**Expected behaviour**:
A servicemonitor that matches metrics port from vault service

**Steps to reproduce the bug**:
Using vault-operator, deploy vault with serviceMonitorEnabled: true.

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.20.10
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): any
- bank-vaults version (e.g. 0.4.17): 1.14.1
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
Servicemonitor:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    banzaicloud.com/last-applied: eyJzcGVjIjp7ImpvYkxhYmVsIjoidmF1bHQiLCJlbmRwb2ludHMiOlt7InBvcnQiOiJwcm9tZXRoZXVzIiwiaW50ZXJ2YWwiOiIzMHMifV0sInNlbGVjdG9yIjp7Im1hdGNoTGFiZWxzIjp7ImFwcC5rdWJlcm5ldGVzLmlvL25hbWUiOiJ2YXVsdCIsInZhdWx0X2NyIjoidmF1bHQifX0sIm5hbWVzcGFjZVNlbGVjdG9yIjp7Im1hdGNoTmFtZXMiOlsia2Vvcy1jb3JlIl19fSwibWV0YWRhdGEiOnsibmFtZXNwYWNlIjoia2Vvcy1jb3JlIiwibGFiZWxzIjp7ImFwcC5rdWJlcm5ldGVzLmlvL25hbWUiOiJ2YXVsdCIsInZhdWx0X2NyIjoidmF1bHQifSwib3duZXJSZWZlcmVuY2VzIjpbeyJibG9ja093bmVyRGVsZXRpb24iOnRydWUsImFwaVZlcnNpb24iOiJ2YXVsdC5iYW56YWljbG91ZC5jb20vdjFhbHBoYTEiLCJraW5kIjoiVmF1bHQiLCJuYW1lIjoidmF1bHQiLCJ1aWQiOiI4YTgyOGRiYS02MGVmLTQ0NTctYmY5YS00NzQ3ZjRmMWNmYmQiLCJjb250cm9sbGVyIjp0cnVlfV0sIm5hbWUiOiJ2YXVsdCJ9fQ==
  labels:
    app.kubernetes.io/name: vault
    vault_cr: vault
  name: vault
  namespace: keos-core
spec:
  endpoints:
  - interval: 30s
    port: prometheus
  jobLabel: vault
  namespaceSelector:
    matchNames:
    - keos-core
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
      vault_cr: vault
```
Service:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    banzaicloud.com/last-applied: eyJzcGVjIjp7InBvcnRzIjpbeyJwb3J0Ijo4MjAwLCJuYW1lIjoiYXBpLXBvcnQifSx7Im5hbWUiOiJjbHVzdGVyLXBvcnQiLCJwb3J0Ijo4MjAxfSx7InBvcnQiOjkwOTEsIm5hbWUiOiJtZXRyaWNzIn0seyJuYW1lIjoic3RhdHNkIiwicG9ydCI6OTEwMn1dLCJzZWxlY3RvciI6eyJhcHAua3ViZXJuZXRlcy5pby9uYW1lIjoidmF1bHQiLCJ2YXVsdF9jciI6InZhdWx0In0sInR5cGUiOiJDbHVzdGVySVAifSwic3RhdHVzIjp7ImxvYWRCYWxhbmNlciI6e319LCJtZXRhZGF0YSI6eyJuYW1lIjoidmF1bHQiLCJuYW1lc3BhY2UiOiJrZW9zLWNvcmUiLCJsYWJlbHMiOnsidmF1bHRfY3IiOiJ2YXVsdCIsImdsb2JhbF9zZXJ2aWNlIjoidHJ1ZSIsImFwcC5rdWJlcm5ldGVzLmlvL25hbWUiOiJ2YXVsdCJ9LCJvd25lclJlZmVyZW5jZXMiOlt7ImtpbmQiOiJWYXVsdCIsIm5hbWUiOiJ2YXVsdCIsInVpZCI6IjhhODI4ZGJhLTYwZWYtNDQ1Ny1iZjlhLTQ3NDdmNGYxY2ZiZCIsImNvbnRyb2xsZXIiOnRydWUsImJsb2NrT3duZXJEZWxldGlvbiI6dHJ1ZSwiYXBpVmVyc2lvbiI6InZhdWx0LmJhbnphaWNsb3VkLmNvbS92MWFscGhhMSJ9XX19
  labels:
    app.kubernetes.io/name: vault
    global_service: "true"
    vault_cr: vault
  name: vault
  namespace: keos-core
spec:
  clusterIP: 10.233.29.204
  clusterIPs:
  - 10.233.29.204
  ports:
  - name: api-port
    port: 8200
    protocol: TCP
    targetPort: 8200
  - name: cluster-port
    port: 8201
    protocol: TCP
    targetPort: 8201
  - name: metrics
    port: 9091
    protocol: TCP
    targetPort: 9091
  - name: statsd
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app.kubernetes.io/name: vault
    vault_cr: vault
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
/kind bug

**Comment by bonifaido** [comment]
Could you please share you Vault Custom Resource YAML?

**Comment by forselli-stratio** [comment]
Hi @bonifaido , here it is:
```
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  namespace: keos-core
spec:
  annotations: null
  bankVaultsImage: docker.io/banzaicloud/bank-vaults:latest
  caNamespaces:
  - vswh
  config:
    api_addr: https://vault.keos-core:8200
    listener:
      tcp:
        address: 0.0.0.0:8200
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    max_lease_ttl: 438000h
    plugin_directory: /vault/plugins
    storage:
      etcd:
        address: https://etcd-cluster.keos-core:2379
        etcd_api: v3
        ha_enabled: "true"
        tls_ca_file: /vault/tls/ca.crt
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    telemetry:
      statsd_address: localhost:9125
    ui: true
  credentialsConfig:
    env: ""
    path: ""
    secretName: ""
  envsConfig: null
  etcdSize: -1
  etcdVersion: ""
  existingTlsSecretName: keos-vault-cert-tls
  externalConfig:
    auth:
    - options:
        max_lease_ttl: 438000h
      roles:
      - bound_service_account_names:
        - '*'
        bound_service_account_namespaces:
        - '*'
        max_ttl: 1h
        name: default
        period: 10m
        policies:
        - open
        ttl: 0
      - bound_service_account_names:
        - '*'
        bound_service_account_namespaces:
        - keos-auth
        max_ttl: 0
        name: sis
        period: 438000h
        policies:
        - sis
        ttl: 0
      - bound_service_account_names:
        - '*'
        bound_service_account_namespaces:
        - '*'
        max_ttl: 0
        name: tais
        period: 438000h
        policies:
        - tais
        ttl: 0
      - bound_service_account_names:
        - tenant-operator
        bound_service_account_namespaces:
        - keos-core
        max_ttl: 0
        name: tenant-operator
        period: 438000h
        policies:
        - tenant-operator
        ttl: 0
      - bound_service_account_names:
        - '*'
        bound_service_account_namespaces:
        - keos-cct
        max_ttl: 0
        name: cct
        period: 438000h
        policies:
        - cct
        ttl: 0
      type: kubernetes
    - options:
        max_lease_ttl: 438000h
      roles:
      - bind_secret_id: true
        name: open
        period: 10m
        policies:
        - open
        secret_id_bound_cidrs: null
        secret_id_num_uses: 1
        secret_id_ttl: 10m
        token_max_ttl: 1h
        token_num_uses: 0
        token_ttl: 0
      - bind_secret_id: true
        name: sis
        period: 438000h
        policies:
        - sis
        secret_id_bound_cidrs: null
        secret_id_num_uses: 1
        secret_id_ttl: 10m
        token_max_ttl: 0
        token_num_uses: 0
        token_ttl: 0
      - bind_secret_id: true
        name: tais
        period: 438000h
        policies:
        - tais
        secret_id_bound_cidrs: null
        secret_id_num_uses: 1
        secret_id_ttl: 10m
        token_max_ttl: 0
        token_num_uses: 0
        token_ttl: 0
      type: approle
    - options:
        max_lease_ttl: 438000h
      roles:
      - allowed_policies:
        - stratio_webhook
        explicit_max_ttl: 0
        name: stratio_vault_secrets_webhook
        period: 438000h
        renewable: true
      - allowed_policies:
        - sis
        explicit_max_ttl: 0
        name: sis
        period: 438000h
        renewable: true
      - allowed_policies:
        - ingress-nginx
        explicit_max_ttl: 0
        name: ingress-nginx
        period: 438000h
        renewable: true
      - allowed_policies:
        - secrets-operator
        explicit_max_ttl: 0
        name: secrets-operator
        period: 438000h
        renewable: true
      type: token
    policies:
    - name: open
      rules: |
        path "sys/*"
        {
          capabilities = ["deny"]
        }
        path "/auth/token/*"
        {
          capabilities = ["deny"]
        }
        path "/*"
        {
          capabilities = ["create", "read", "update", "list"]
        }
    - name: stratio_webhook
      rules: |
        path "sys/*"
        {
          capabilities = ["deny"]
        }
        path "/auth/approle/*"
        {
          capabilities = ["create", "read", "update", "list"]
        }
    - name: tais
      rules: |
        path "/*"
        {
          capabilities = ["create", "read", "update", "list"]
        }
    - name: sis
      rules: |
        path "sys/*"
        {
          capabilities = ["deny"]
        }
        path "/ca-trust/*"
        {
          capabilities = ["read", "list"]
        }
        path "/userland/*"
        {
          capabilities = ["read", "list"]
        }
        path "/secret/*"
        {
          capabilities = ["create", "read", "update", "delete", "list"]
        }
        path "/auth/token/*"
        {
          capabilities = ["create", "read", "update", "list"]
        }
    - name: ingress-nginx
      rules: |
        path "/userland/certificates/*"
        {
          capabilities = ["read"]
        }
    - name: secrets-operator
      rules: |
        path "userland/*"
        {
          capabilities = ["create", "read", "update", "list", "delete"]
        }
        path "/people/*"
        {
          capabilities = ["create", "read", "update", "list", "delete"]
        }
        path "pki/issue/*"
        {
          capabilities = ["create", "update"]
        }
        path "pkis/+/issue/*"
        {
          capabilities = ["create", "update"]
        }
        path "sys/policies/*"
        {
          capabilities = ["create", "read", "update", "delete"]
        }
        path "/auth/kubernetes/role/*"
        {
          capabilities = ["create", "read", "update", "delete"]
        }
        path "/kerberos-eos/*"
        {
          capabilities = ["create", "read", "update", "delete"]
        }
    - name: tenant-operator
      rules: |
        path "userland/+/tenant-operator.*" {
          capabilities = ["list", "read"]
        }
        path "ca-trust/certificates/*" {
          capabilities = ["list", "read"]
        }

        path "sys/mounts" {
          capabilities = ["list", "read"]
        }

        path "sys/mounts/pkis/*" {
          capabilities = ["create", "update", "delete"]
        }

        path "pkis/*" {
          capabilities = ["create", "update"]
        }

        path "pki/*" {
          capabilities = ["create", "update"]
        }
    - name: cct
      rules: |
        path "/*"
        {
          capabilities = ["read","list"]
        }
        path "/userland/*"
        {
          capabilities = ["create", "read", "update", "list", "delete"]
        }
        path "/people/*"
        {
          capabilities = ["create", "read", "update", "list", "delete"]
        }
        path "/sys/mounts/*"
        {
          capabilities = ["create", "read", "update", "list"]
        }
        path "/pki*"
        {
          capabilities = ["create", "read", "update", "list"]
        }
        path "/kerberos-eos/*"
        {
          capabilities = ["create", "read", "update", "list"]
        }
    secrets:
    - description: General secrets.
      options:
        version: 1
      path: secret
      type: kv
    - description: Userland secrets.
      options:
        version: 1
      path: userland
      type: kv
    - description: CA secrets.
      options:
        version: 1
      path: ca-trust
      type: kv
    - description: People secrets.
      options:
        version: 1
      path: people
      type: kv
    - config:
        default_lease_ttl: 168h
        max_lease_ttl: 87600h
      configuration:
        config:
        - crl_distribution_points: https://vault.keos-core:8200/v1/pki/crl
          issuing_certificates: https://vault.keos-core:8200/v1/pki/ca
          name: urls
        roles:
        - allow_bare_domains: true
          allow_glob_domains: true
          allowed_domains: '*'
          enforce_hostnames: false
          max_ttl: 43800h
          name: tais
          ttl: 43800h
        - allow_bare_domains: true
          allow_glob_domains: true
          allowed_domains: '*'
          basic_constraints_valid_for_non_ca: true
          client_flag: true
          enforce_hostnames: false
          key_usage:
          - DigitalSignature
          - KeyAgreement
          - KeyEncipherment
          max_ttl: 43800h
          name: dcs-client-server
          server_flag: true
          ttl: 43800h
        - allow_bare_domains: true
          allow_glob_domains: true
          allowed_domains: '*'
          basic_constraints_valid_for_non_ca: true
          client_flag: true
          enforce_hostnames: false
          key_usage:
          - DigitalSignature
          max_ttl: 43800h
          name: dcs-client
          server_flag: false
          ttl: 43800h
        - allow_bare_domains: true
          allow_glob_domains: true
          allowed_domains: '*'
          basic_constraints_valid_for_non_ca: true
          client_flag: false
          enforce_hostnames: false
          key_usage:
          - DigitalSignature
          - KeyAgreement
          - KeyEncipherment
          max_ttl: 43800h
          name: dcs-server
          server_flag: true
          ttl: 43800h
      description: Vault PKI Backend
      type: pki
    startupSecrets:
    - data:
        keos-ca-root_crt: '-----BEGIN CERTIFICATE-----MIIE9jCCAt6gAwIBAgIUVdefY3I9It1KiPt60GFHpRyz1a0wDQYJKoZIhvcNAQELBQAwEzERMA8GA1UEAwwIa2Vvc2RldjIwHhcNMjEwOTIzMTIzMDA5WhcNMzEwOTIxMTIzMDA5WjATMREwDwYDVQQDDAhrZW9zZGV2MjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKfv9OwFtjWH1OK/sGCAiQi8y5fsOmRZl1yQXL1FS0HbPAhYRNnjRScB9Wott/scwrxOR52y/Dfa7iy0B2Isj/0MkcNFDZLA09xZhGtGoJ89QhlCva3jep7LJ+VULp5eO+KLOVWpJaOt439cfGMC5TJd2rfpM5bJHiDumqkr+8eUkc0VaGv4M5BP8fdxeHZE8S2v/bcEBo5Kli9tkpPzzc4ygazwHLjOdCEmp5EapncZVes0yENynMbT5QN8ZTnrZqUMC+PjQL+GolS+8iJlJ85iMpcoKBfcpoSvqyQvXLRpn0fVRWqxYkgyrMuBIbj2to3PBSMfUDm2s4Deo0WOaUDKArMPn5M+PmsUBJ66OBP8Z3occbfIWmx0kIwhaaB5+zv6ksRANGNavtLDzYKYEKBCJrec3p92SWBF9ilqztMgqO9MQEgz+I8LiKj95zL+JNsOvz/n6ut3VIfCksjVttP1wagUfNLI1cxNDu2JPTz0suzOmC6To9DeQZnzGIuBFku4g56C29dIgHnMqOorOFZBHBQOclH2SPpo+GlQrgde3uS8qYW++bL4/+/ai6D2qNR3ns5e8S3PgwV7zINZbtiuuevkXseDAR6zEGkqi13NEXV/gEcwa4yUNMTnFws7lGG2YbqHjJb50oae5s2dVkoAdlKpbVpsDmIbBAIo/M11AgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQUcy0i+v6DTub3x89dp5W7YgcVHjANBgkqhkiG9w0BAQsFAAOCAgEALlc0j2pA7wWqYQL6kvklQWmBipmDuQwcO66hSXOY1wMzGkooQIgzmvV513SHjnRzoTFz3flOw6b2K7Vpzzt9s/W6MgZ0B7jpBAFsyACh/UB80XyLG7iyB9FAQs61AGDff7rEGOfREV+6S5zUhnF3Cu8iKkhiRhtyVADJ/aGKwwaucmR9semBUqdm3WzU1RJAJ8943n+cAyGqj36YsUo7Ufql0JuEKarzOCtSJaqaKZOlUeqy5lYJ0h6DLtFhD3J0495QAGUGiV9skBgBm7Nc0+I/zKD5tHIlToWRoDrk+oxm4JjfvNuYXg9N93FKjpKIFpwaksuI0y8TG3aOgENfEprizP81Uz6gu0q0pA94IF/QValVScbFs+Cad/Nz6FfdtguRFe7mEGOfAKyuwKZqBZ5CDK+J5c5PUZ26GAGPfyxA2UgDJ7hqfaMO5AsIrDUwE4KIa/I1TAEvGF5OKP+j8+/XIL/mNevwt5YBaokM0r/sEPUF6T1r863ImkVfd9ixe7lnQx75Js+3RIetlrSEctZBRHRFE3B1hQHi6vcxPI7b+jFK2dM7k5pvyAHjT0Bmdt/0H3tuYbTOjH/+VSFGUxc3U2jBVlyrbaFzpw3UdyVuIi4L8aI3zlwDUqm4n0r7yrNbgk0LVj+YlJTeX9tePr8vHR6Hlzx8x8wdoC4qycs=-----END
          CERTIFICATE-----'
      path: ca-trust/certificates/keos-ca-root
      type: kv
    - data:
        pass: 14k005Pj7Edwd537X85315TP9ittTYWBfEcCvGc3
      path: ca-trust/passwords/default/keystore
      type: kv
    - data:
        secretKeyRef:
        - key: ca.crt
          name: keos-vault-cert-tls
        - key: ca.key
          name: keos-vault-cert-tls
      path: pki/config/ca
      type: pki
  fluentdConfig: ""
  fluentdEnabled: false
  fluentdImage: ""
  image: qa.int.stratio.com/stratio/vault-kerberos:0.5.0-7e89be1
  nodeAffinity: {}
  nodeSelector: null
  podAntiAffinity: ""
  raftLeaderAddress: ""
  securityContext: {}
  serviceAccount: vault-operator
  serviceMonitorEnabled: true
  servicePorts: null
  serviceType: ""
  size: 3
  statsdDisabled: false
  statsdImage: docker.io/prom/statsd-exporter:latest
  tolerations: null
  unsealConfig:
    kubernetes:
      secretName: ""
      secretNamespace: keos-core
    options: {}
  vaultAnnotations: null
  vaultConfigurerAnnotations: null
  vaultConfigurerLabels: null
  vaultConfigurerPodSpec:
    containers: null
  vaultEnvsConfig:
  - name: VAULT_CACERT
    value: /vault/tls/ca.crt
  vaultLabels: null
  vaultPodSpec:
    containers: null
  veleroFsfreezeImage: ""
  volumeMounts:
  - mountPath: /etc/krb5.conf
    name: krb5-config
    subPath: krb5.conf
  - mountPath: /vault/plugins/keos-admin.keytab
    name: admin-keytab-secret
    subPath: keos-admin.keytab
  volumes:
  - configMap:
      items:
      - key: krb5.conf
        path: krb5.conf
      name: keos-kerberos-config
    name: krb5-config
  - name: admin-keytab-secret
    secret:
      items:
      - key: admin-keytab
        path: keos-admin.keytab
      secretName: keos-kerberos-secrets
  watchedSecretsAnnotations: null
  watchedSecretsLabels: null


```
