### ISSUE TITLE
"MutatingAdmissionWebhook" failed to complete mutation in 13s using External Vault integrate with Openshift 4.7

### ISSUE THREAD

**Issue by ahmadsyahidr** [bank-vaults/bank-vaults#1441]
> **Error from server (InternalError): error when creating "STDIN": Internal error occurred: admission plugin "MutatingAdmissionWebhook" failed to complete mutation in 13s**

**Describe the bug**:
I got above error whenever I try to create a test pods which having env variable that should be mutated by the webhook.
>      - name: AWS_SECRET_ACCESS_KEY
>        value: vault:secret/data/demosecret/aws#AWS_SECRET_ACCESS_KEY
The result is failed to create the pods.

**Expected behaviour**:
The pods is created, init-containers copy-vault-env is injected automatically by the webhook, and env variable should be updated. the env variable value can be check by running command :
> vault-env env | grep aws

**Steps to reproduce the bug**:
1. Install and configure external vault.
2. Connect external Vault with Openshift 4.7.23 (k8s version v1.20.0+558d959) using oc client version 4.5.0-0.okd-2020-10-03-012432
3. Create an endpoints and external service for the external vault:

```
EXTERNAL_VAULT_ADDR=172.18.136.93
EXTERNAL_VAULT_PORT=4004
oc apply -f - <<EOF
---
apiVersion: v1
kind: Service
metadata:
  name: external-vault
  namespace: brimo
spec:
  ports:
  - protocol: TCP
    port: 4004
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-vault
subsets:
  - addresses:
      - ip: $EXTERNAL_VAULT_ADDR
    ports:
      - port: $EXTERNAL_VAULT_PORT
EOF
```
4. Install vault agent injector only via helm
helm install vault hashicorp/vault \
    --set "injector.externalVaultAddr=http://external-vault:4004"
5. Configure Kubernetes authentication:
```
VAULT_HELM_SECRET_NAME=$(kubectl get secrets --output=json | jq -r '.items[].metadata | select(.name|startswith("vault-token-")).name')

TOKEN_REVIEW_JWT=$(kubectl get secret $VAULT_HELM_SECRET_NAME --output='go-template={{ .data.token }}' | base64 --decode)
KUBE_CA_CERT=$(kubectl config view --raw --minify --flatten --output='jsonpath={.clusters[].cluster.certificate-authority-data}' | base64 --decode)
KUBE_HOST=$(kubectl config view --raw --minify --flatten --output='jsonpath={.clusters[].cluster.server}')
```
```
vault write auth/kubernetes/config \
        token_reviewer_jwt="$TOKEN_REVIEW_JWT" \
        kubernetes_host="$KUBE_HOST" \
        kubernetes_ca_cert="$KUBE_CA_CERT" \
        issuer="https://kubernetes.default.svc"
```
6. Set New policy and roles:
```
vault policy write allow_secrets - <<EOF
path "secret/*" {  
  capabilities = ["create", "read", "update", "delete", "list"]
}
EOF

vault write auth/kubernetes/role/default \
        bound_service_account_names='default' \
        bound_service_account_namespaces='myapps' \
        policies='allow_secrets' \
        ttl=24h
```

7. Create a test pods with banzai annotation to test:
```
oc apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: devwebapp
  labels:
    app: devwebapp
  annotations:
    vault.security.banzaicloud.io/vault-addr: "http://external-vault:4004"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-skip-verify: "false"
    vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
    vault.security.banzaicloud.io/vault-agent: "true"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
spec:
  serviceAccountName: default
  containers:
    - name: app
      image: burtlo/devwebapp-ruby:k8s
      env:
      - name: VAULT_ADDR
        value: "http://external-vault:4004"
      - name: VAULT_TOKEN
        value: ***********************
      - name: AWS_SECRET_ACCESS_KEY
        value: vault:secret/data/demosecret/aws#AWS_SECRET_ACCESS_KEY
EOF
```

**Additional context**:

**Environment details**:
- Vault version 1.8.4
- Helm version 3.7.0
- Openshift server version 4.7
- Openshift client version 4.5.0-0.okd-2020-10-03-012432
- k8s version v1.20.0+558d959
- CHART version vault-secrets-webhook-1.14.5 
- APP version 1.14.1
