### ISSUE TITLE
Cannot deploy  vault-operator while providing `global.imagePullSecrets`

### ISSUE THREAD

**Issue by j-zimnowoda** [bank-vaults/bank-vaults#1461]
**Describe the bug**:
The dependency of etcd-operator does not produce correct manifest fo ServiceAccount.

Providing values:
```
# values.yaml
global:
  imagePullSecrets: 
  - my-pull-secret
```

The helm generates ServiceAccount for etcd-operator
```
# Source: vault-operator/charts/etcd-operator/templates/operator-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-operator-etcd-operator-etcd-operator
  labels:
    chart: "etcd-operator-0.11.0"
    app: etcd-operator
    heritage: Helm
    release: vault-operator
imagePullSecrets: 
  - my-pull-secret
```
Which cause error while deploying:
```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(ServiceAccount.imagePullSecrets[0]): invalid type for io.k8s.api.core.v1.LocalObjectReference: got "string", expected "map"
```
**Expected behaviour**:
A concise description of what you expected to happen.
The expected manifest for ServiceAccount is:
```
# Source: vault-operator/charts/etcd-operator/templates/operator-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-operator-etcd-operator-etcd-operator
  labels:
    chart: "etcd-operator-0.11.0"
    app: etcd-operator
    heritage: Helm
    release: vault-operator
imagePullSecrets: 
  - name: my-pull-secret
```

See `name` property at `imagePullSecrets`
Refer to: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-image-pull-secret-to-service-account

**Steps to reproduce the bug**:
described above

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.21
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): n/a
- bank-vaults version (e.g. 0.4.17): 1.14.3
- Install method (e.g. helm or static manifests): helm

/kind bug
