### ISSUE TITLE
Vault-CRD: add env to bank-vaults sidecar

### ISSUE THREAD

**Issue by Poweranimal** [bank-vaults/bank-vaults#1483]
**Is your feature request related to a problem? Please describe.**
Make it possible to pass environment variables to the `bank-vaults` sidecar of the `Vault` crd.
This would make it possible to pass the parameters needed for `unsealConfig` to be fetched from a `Secret` or `ConfigMap`.

**Describe the solution you'd like**
Adding something similar like `vaultContainerSpec` for the `bank-vaults` container to the `Vault` crd.
This would allow the following:
```yaml
...

bankVaultsContainerSpec:
  name: bank-vaults
  env:
   - name: "AWS_KMS_KEY_ID"
     valueFrom:
       configMapKeyRef:
         name: aws-config
         key: kms-key-id
...

unsealConfig:
  aws:
    kmsKeyId: $(AWS_KMS_KEY_ID)

```

**Describe alternatives you've considered**
Something similar is possible by using the standalone `bank vaults` helm chart:

```yaml
vault:
  envSecrets:
  - secretName: "vault-aws",
    secretKey: "kms-key-id",
    envName: "AWS_KMS_KEY_ID",

   - secretName: "vault-aws",
     secretKey: "kms-region",
     envName: "AWS_KMS_REGION",

   - secretName: "vault-aws",
     secretKey: "s3-bucket",
     envName: "AWS_S3_BUCKET",

   - secretName: "vault-aws",
     secretKey: "s3-region",
     envName: "AWS_S3_REGION",

...

unsealer:
  args: [
      "--mode", "aws-kms-s3",
      "--aws-kms-key-id", "$(AWS_KMS_KEY_ID)",
      "--aws-kms-region", "$(AWS_KMS_REGION)",
      "--aws-s3-bucket", "$(AWS_S3_BUCKET)",
      "--aws-s3-region", "$(AWS_S3_REGION)",
  ]
...
```
