### ISSUE TITLE
vault container enters not ready state unpredictably.

### ISSUE THREAD

**Issue by derekwilliamsliquidx** [bank-vaults/bank-vaults#1485]
**Describe the bug**:
Every so often the vault container inside the vault-x pod will enter a not ready state and not restart causing requests to Vault API to fail. This is not reproducible by will. It happens every few weeks in ALL 4 of our environments (4 separate installations). No logs are (even with debug enabled) are present when the failure happens. Our monitoring show NO increase in CPU/memory/network utilization. One theory we do have is that we use External Secrets engine to automatically create secrets. The polling interval for over 200 secrets is every 60 seconds. The issue with this theory is the resource usage. All metrics are normal for hours prior to the failure. Something is happening here and the vault container isn't logging anything.

**Expected behaviour**:
Container should not crash OR if it does, the pod is restarted.

**Steps to reproduce the bug**:
I cannot reproduce this. I just have to wait. But this happens in all 4 environments, on separate Kubernetes clusters. I should also note that we are in the middle of a K8s upgrade and it happens on two separate version.

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.21.2 AND 1.20.7
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): AKS
- bank-vaults version (e.g. 0.4.17): 1.13.1
- Vault Version: 1.7.3
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): NO LOGS when this happens. None. Everything appears normal but it is very much not normal
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
```yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
  namespace: secret-infra
spec:
  size: 3
  image: vault:1.7.3
  bankVaultsImage: banzaicloud/bank-vaults:1.13.1

  podAntiAffinity: kubernetes.io/hostname

  resources:
    vault:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 512Mi
  vaultContainerSpec:
    name: "vault"
    readinessProbe:
      periodSeconds: 10
      timeoutSeconds: 5
      
  # Common annotations for all created resources
  annotations:
    common/annotation: "true"

  # Vault Pods , Services and TLS Secret annotations
  vaultAnnotations:
    type/instance: "vault"

  # Vault Configurer Pods and Services annotations
  vaultConfigurerAnnotations:
    type/instance: "vaultconfigurer"

  # Vault Pods , Services and TLS Secret labels
  vaultLabels:
    example.com/log-format: "json"

  # Vault Configurer Pods and Services labels
  vaultConfigurerLabels:
    example.com/log-format: "string"

  vaultEnvsConfig:
    - name: VAULT_LOG_LEVEL
      value: {{ .Values.vault.logging.level }}


  # Support for nodeAffinity Rules
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: purpose
          operator: NotIn
          values:
          - ml

  # Support for pod nodeSelector rules to control which nodes can be chosen to run
  # the given pods
  # nodeSelector:
  #   "node-role.kubernetes.io/your_role": "true"

  # Support for node tolerations that work together with node taints to control
  # the pods that can like on a node
  # tolerations:
  # - effect: NoSchedule
  #   key: node-role.kubernetes.io/your_role
  #   operator: Equal
  #   value: "true"

  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: vault

  # Specify the Service's type where the Vault Service is exposed
  # Please note that some Ingress controllers like https://github.com/kubernetes/ingress-gce
  # forces you to expose your Service on a NodePort
  serviceType: ClusterIP

  # Specify existing secret contains TLS certificate (accepted secret type: kubernetes.io/tls)
  # If it is set, generating certificate will be disabled
  # existingTlsSecretName: selfsigned-cert-tls
  existingTlsSecretName: ""
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/ingress-class: nginx
      kubernetes.io/ingress.allow-http: "false"
    spec: 
      rules:
      - host: "vault{{ .Values.ingress.namespaceSubDomain }}{{ .Values.ingress.domain }}"
        http:
          paths:
          - backend:
              serviceName: vault
              servicePort: 8200
            path: /
      tls:
      - hosts:
        - "vault{{ .Values.ingress.namespaceSubDomain}}{{ .Values.ingress.domain }}"
        secretName: tls-vault-external

  # Support for distributing the generated CA certificate Secret to other namespaces.
  # Define a list of namespaces or use ["*"] for all namespaces.
  caNamespaces:
    - "*"

  # Describe where you would like to store the Vault unseal keys and root token.
  unsealConfig:
    options:
      # The preFlightChecks flag enables unseal and root token storage tests
      # This is true by default
      preFlightChecks: true
    kubernetes:
      secretNamespace: secret-infra

  # A YAML representation of a final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    storage:
{{- if hasKey .Values.vault.backend "postgres" }}
      postgresql:
        connection_url: {{ .Values.vault.backend.postgres.connection_url }}
        max_idle_connections: 30
        max_open_connections: {{ .Values.vault.backend.postgres.max_idle_connections }}
        ha_enabled: {{ .Values.vault.backend.postgres.ha_enabled }}
{{- else }}
      file:
        path: "{{ .Values.vault.backend.file.path }}"
{{- end }} 
    listener:
      tcp:
        address: "0.0.0.0:8200"
        # Uncommenting the following line and deleting tls_cert_file and tls_key_file disables TLS
        # tls_disable: true
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    telemetry:
      statsd_address: localhost:9125
    ui: true
    api_addr: "https://vault.secret-infra:8200"
    cluster_addr: "https://vault.secret-infra:8201"

  # See: https://github.com/banzaicloud/bank-vaults#example-external-vault-configuration for more details.
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: allow_pki
        rules: path "pki/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: allow_transit
        rules: path "transit/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: admin
        rules: path "sys/health" {
                  capabilities = ["read", "sudo"]
                } path "sys/policies/acl"
                {
                  capabilities = ["list"]
                } path "sys/policies/acl/*"
                {
                  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
                } path "auth/*"
                {
                  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
                } path "sys/auth/*"
                {
                  capabilities = ["create", "update", "delete", "sudo"]
                } path "sys/auth"
                {
                  capabilities = ["read"]
                } path "secret/*"
                {
                  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
                } path "sys/mounts/*"
                {
                  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
                } path "sys/mounts"
                {
                  capabilities = ["read"]
                }
    auth:
    - roles:
      - name: app_auth
        token_ttl: 0
        token_policies:
        - allow_secrets
        - allow_pki
        - allow_transit
      type: approle

    - roles:
      - bound_service_account_names:
        - '*'
        bound_service_account_namespaces:
        - secret-infra
        - vswh
        - {{ .Values.global.environment }}
{{- if eq .Values.global.environment "uat"}}
        - demo
{{- end }}
        name: secret-infra
        policies:
        - allow_secrets
        - allow_pki
        - allow_transit
        ttl: 1h
      type: kubernetes
    
# Give Devs Access to Development Vault
    - roles:
      - user_claim: email
        allowed_redirect_uris:
        - <REDACTED>
        - <REDACTED>
        policies:
        - allow_secrets
        - allow_pki
        - allow_transit
        ttl: 24h
        name: developer
      bound_group_ids: {{ .Values.vault.rbac.groups.developers }}
      config:
        oidc_client_id: ${ .Env.AZURE_OIDC_CLIENT_ID }
        oidc_client_secret: ${ .Env.AZURE_OIDC_CLIENT_SECRET }
        oidc_discovery_url:  <REDACTED>
        default_role: developer
      options:
        listing_visibility: unauth

      type: oidc
    
    groups:
    - name: AZ_DEV
      policies:
        - allow_secrets
        - allow_pki
        - allow_transit
      metadata:
        admin: "true"
        priviliged: "true"
      type: external
    
### Admin Role For DevOps
    - roles:
      - user_claim: email
        allowed_redirect_uris:
        -  <REDACTED>
        -  <REDACTED>
        policies:
        - allow_secrets
        - allow_pki
        - allow_transit
        ttl: 24h
        name: admin
      bound_group_ids: {{ .Values.vault.rbac.groups.devops }}
      config:
        oidc_client_id: ${ .Env.AZURE_OIDC_CLIENT_ID }
        oidc_client_secret: ${ .Env.AZURE_OIDC_CLIENT_SECRET }
        oidc_discovery_url:  <REDACTED>
        default_role: developer
      options:
        listing_visibility: unauth
      type: oidc


    groups:
    - name: DevOps
      policies:
        - admin
      metadata:
        admin: "true"
        priviliged: "true"
      type: external


    secrets:
    - description: General secrets.
      options:
        version: 2
      path: secret
      type: kv
    - description: Transit Secret Engine for Encryption Keys.
      path: transit
      type: transit
    - config:
        default_lease_ttl: 168h
        max_lease_ttl: 720h
      configuration:
        config:
        - crl_distribution_points:  <REDACTED>
          issuing_certificates: <REDACTED>
          name: urls
        roles:
        - allow_subdomains: true
          allowed_domains: localhost,pod,svc,secret-infra
          generate_lease: true
          name: secret-infra
          ttl: 1m
        root/generate:
        - common_name: vault.secret-infra
          name: internal
      description: Vault PKI Backend
      type: pki

    # Allows writing some secrets to Vault (useful for development purposes).
    # See https://www.vaultproject.io/docs/secrets/kv/index.html for more information.
    startupSecrets:
      - type: kv
        path: secret/data/accounts/aws
        data:
          data:
            AWS_ACCESS_KEY_ID:  <REDACTED>
            AWS_SECRET_ACCESS_KEY:  <REDACTED>
      - type: kv
        path: secret/data/dockerrepo
        data:
          data:
            DOCKER_REPO_USER:  <REDACTED>
            DOCKER_REPO_PASSWORD:  <REDACTED>
      - type: kv
        path: secret/data/mysql
        data:
          data:
            MYSQL_ROOT_PASSWORD:  <REDACTED>
            MYSQL_PASSWORD:  <REDACTED>
  envsConfig:
  - name: AZURE_OIDC_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: azure-oidc-client
        key: AZURE_OIDC_CLIENT_ID
  - name: AZURE_OIDC_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: azure-oidc-client
        key: AZURE_OIDC_CLIENT_SECRET

  vaultEnvsConfig:
    - name: VAULT_LOG_LEVEL
      value: info

  # Marks presence of Istio, which influences things like port namings
  istioEnabled: false
```

/kind bug
