### ISSUE TITLE
Can't enable secret plugin in 1.15.0

### ISSUE THREAD

**Issue by pabardina** [bank-vaults/bank-vaults#1544]
**Describe the bug**:
Hello! Since 1.15.0, I can't enable a secret plugin. I got the error : 

```
{"level":"error","msg":"error configuring vault: error configuring secret engines for vault: error adding managed secrets engines: error mounting artifactory into vault: Error making API request.\n\nURL: POST http://vault.vault:8200/v1/sys/mounts/artifactory\nCode: 400. Errors:\n\n* plugin_name must be provided for plugin backend","time":"2022-02-17T15:58:11Z"}
```
If I roll back to 1.14.2, it works as attended.

It seems that the plugin_name is always empty.

**Expected behaviour**:

I can enable a secret plugin.

**Steps to reproduce the bug**:

My configuration : 

```
    secrets:
      - path: artifactory
        plugin_name: name
        type: plugin
```

Thanks

/kind bug

**Comment by bonifaido** [comment]
Can this be the root cause? https://github.com/banzaicloud/bank-vaults/pull/1519 @aabouzaid ?

**Comment by aabouzaid** [comment]
@pabardina could you please provide a full example to reproduce the issue?

Also is not a valid config:
```
secrets:
  - path: artifactory
    plugin_name: name
    type: plugin
```

You need to set the actual plugin name in `plugin_name`.
