### ISSUE TITLE
function "username" not defined after configuring posgresql secret engine

### ISSUE THREAD

**Issue by naydoo** [bank-vaults/bank-vaults#1559]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
I tried to configure the postgres secret engine via the vault cr manifest. Below are the configs.
```
secrets:
      - type: kubernetes
        description: PostgreSQL Database secret engine.
        configuration:
          config:
          - name: testrole
            plugin_name: "postgresql-database-plugin"
            connection_url: "postgresql://{{username}}:{{password}}@postgres.postgres:5432/postgres?sslmode=disable"
            allowed_roles: [testrole]
            username: "postgres" # Example how to read environment variables
            password: "postgres"
```

**Expected behaviour**:
database with dynamic secret is created after the vault pod startup successfully
**Actual behaviour**:
I get the error: 

`function "username" not defined`

**Steps to reproduce the bug**:
Add postgresql secret engine to configure postgres database and dynamic secret via the vault CR manifest
Run the command: **_helm install vault-server path/to/vault-cr  --dry-run_**

**Environment details**:
- Kubernetes version: 1.23.3
- Minikube
- bank-vaults version: 1.15.3
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug
