### ISSUE TITLE
Migration or adding ha_storage for existing vault instance 

### ISSUE THREAD

**Issue by rodosskiand** [bank-vaults/bank-vaults#1619]
Hi! I can't find info about the opportunity for switching to/adding ha_storage in the existing vault instance (managed by the operator).
I found a guide: https://learn.hashicorp.com/tutorials/vault/raft-ha-storage and this what I need: updating existing server. But I'm not sure how this can be done correctly via the operator. 

In my case, I use s3 integrated storage and a single vault replica (`size: 1`). Can I just add `ha_storage` parameter (example raft):

```
  config:
    storage:
      s3:
        region: "us-east-1"
        bucket: "vault"
    ha_storage:
      raft:
        path: /vault/raft
    listener:
```
and change the size to 3 (for example)?

Or I should make any extra actions for adding ha_storage?

Thanks!
