### ISSUE TITLE
consul-template fails with `* missing client token`

### ISSUE THREAD

**Issue by moustafab** [bank-vaults/bank-vaults#1635]
**Describe the bug**:
Our setup was working with `1.14.1` but when we upgraded to `1.15.3` any consul-template side-cars started after would error out with: `* missing client token`

**Expected behaviour**:
Consul-template is able to authenticate with vault

**Steps to reproduce the bug**:
Set up a consul-template configuration to get any secret from vault using the annotations.

**Additional context**:
Our pod was running a container as root in a scratch base.

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.23.X
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): AWS kops
- bank-vaults version (e.g. 0.4.17): 1.15.3
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): `400 * missing client token`
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

Deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: foo
      app.kubernetes.io/name: app
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-ct-configmap: consul-template
        vault.security.banzaicloud.io/vault-path: kubernetes
        vault.security.banzaicloud.io/vault-role: default
      labels:
        app.kubernetes.io/instance: foo
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: app
        app.kubernetes.io/version: 0.0.1
    spec:
      containers:
        - env:
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /vault/secrets/aws-creds
          image: 'myimage:latest'
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources: {}
          securityContext: {}
          volumeMounts:
            - mountPath: /app/server/www
              name: static-files
      serviceAccountName: app
      volumes:
        - configMap:
            name: environment-file
          name: static-files
```
consul-template-configmap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: foo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: app
    app.kubernetes.io/version: 0.0.1
  name: consul-template
  namespace: foo
data:
  config.hcl: |
    vault {
      retry {
        backoff = "1s"
      }
    }
    template {
      left_delimiter = "[["
      right_delimiter = "]]"
      
      contents = <<-EOH
      [[- with secret "aws/creds/app" ]]
      [default]
      aws_access_key_id = [[ .Data.access_key ]]
      aws_secret_access_key = [[ .Data.secret_key ]]
      aws_session_token = [[ .Data.security_token ]]
      [[ end ]]
      EOH
      destination = "/vault/secrets/aws-creds"
    }
```

/kind bug
