### ISSUE TITLE
Kube Auth : Incompatibility with K8S 1.21+ "short-lived tokens"

### ISSUE THREAD

**Issue by pbriet** [bank-vaults/bank-vaults#1647]
**Describe the bug**:
* After a given time, all kubernetes authentications fail with "Permission denied"

**Expected behaviour**:
* Kubernetes auth continues to work

**Steps to reproduce the bug**:
* Use K8S 1.21+
* Configure a Kubernetes auth through the vault.banzaicloud.com/v1alpha1/Vault CRD, with defaults (no explicit config) : 
```
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  (...)
  externalConfig:
    auth:
      - type: kubernetes
        roles: (...)
```
* Wait at least 1h
* Start a pod that will use kubernetes auth to retrieve a secret

**Additional context**:

K8S 1.21 introduced "Bound Service Account Token Volume", which implies an automatic rotation of service account tokens.

As explained in the Vault doc  (https://www.vaultproject.io/docs/auth/kubernetes#use-local-service-account-token-as-the-reviewer-jwt)
> To use the local token and CA certificate, omit token_reviewer_jwt and kubernetes_ca_cert when configuring the auth method. Vault will attempt to load them from token and ca.crt respectively inside the default mount folder

I think the problem comes from the `kubernetesAuthConfigDefault` function : https://github.com/banzaicloud/bank-vaults/blob/main/internal/vault/auth_methods.go#L210
It provides explicits JWT & token.

A temporary workaround could be to explicitly set the kubernetes host : 
```
auth:
      - type: kubernetes
        config:
          kubernetes_host: https://kubernetes.default.svc
```

Because of https://github.com/banzaicloud/bank-vaults/blob/main/internal/vault/auth_methods.go#L76

I'm testing the workaround right now, but I'm pretty confident it'll fix it.

A permanent & clean fix would be to stop providing kubernetes_ca_cert & token_reviewer_jwt in kubernetes auth defaults (if Vault 1.9.3+)

**Environment details**:
- Openshift 4.9 (K8S 1.22)
- Bank vaults operator 1.15.2
- Vault 1.10.4

/kind bug

**Comment by pbriet** [comment]
Note : this is kinda critical, and may affect many users.

**Comment by pbriet** [comment]
I confirm that the workaround is successful.

And I'm worried that nobody gives feedback on this critical issue!

We are seriously considering abandoning Bank Vaults because of the lack of stability & support.

**Comment by BojanZelic** [comment]
I also ran into this same issue, but used a similar workaround;

```
      - type: kubernetes
        path: kubernetes
        roles: ...
        config:
            kubernetes_host: https://$${.Env.KUBERNETES_SERVICE_HOST}
            disable_iss_validation: true
            kubernetes_ca_cert: ""
            token_reviewer_jwt: ""
```

**Comment by notjames** [comment]
> I confirm that the workaround is successful.
> 
> And I'm worried that nobody gives feedback on this critical issue!
> 
> We are seriously considering abandoning Bank Vaults because of the lack of stability & support.

this will become critical in EKS when short-lived tokens and OIDC are forced in 1.24

**Comment by suchitsancheti** [comment]
@BojanZelic / @pbriet / @notjames Need your help in enabling the k8s auth and making it work.
I followed what has been suggested here. I have created the k8s auth using the `vault.banzaicloud.com/v1alpha1` CRD as follows:

```
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
  namespace: "vault"
spec:
    auth:
      - type: kubernetes
        path: kubernetes/ops
        config:
          kubernetes_host: https://kubernetes.default.svc
          disable_iss_validation: true
          kubernetes_ca_cert: ""
          token_reviewer_jwt: ""
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: ["issuer"]
            bound_service_account_namespaces: ["cert-manager"]
            policies: ["my-policy", "default"]
            ttl: 5m

```
I am using AWS EKS k8s v1.23. I am trying to setup cert-maanger with Vault. When I am defining the issuer as follows:
```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: cert-manager
spec:
  vault:
    server: http://vault.vault:8200
    path: vaultCA/sign/cluster-local
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes/ops
        role: k8s-ops
        secretRef:
          name: issuer-token-xxxx
          key: token

```
Its giving me permission denied error Failed to initialize Vault client: error reading Kubernetes service account token from issuer-token-r4pkp: error calling Vault server: Error making API request.

Do I need to create a clusterrolebinding for this service account `kubectl create clusterrolebinding vault-client-auth-delegator --clusterrole=system:auth-delegator --serviceaccount=cert-manager:issuer`

Am I missing anything here? Can you please suggest?
