### ISSUE TITLE
Having more than 1 Vault server causes "local node not active but active cluster node not found" on Kubernetes 1.23.5-gke.1503

### ISSUE THREAD

**Issue by gbuirel** [bank-vaults/bank-vaults#1649]
**Describe the bug**:
We use Vault on a GKE Cluster, with : 

- Vault Operator helm chart : 1.15.8
- Vault ressource definition :  vault.banzaicloud.com/v1alpha1
- Vault webhook helm chart : 1.15.11

We recently upgraded our Kubernetes version from 1.23.5-gke.1501 to 1.23.5-gke.1503.

After the upgrade,
when using a size of more than  1 on the Vault ressource, the UI becomes unavailable with the error `"local node not active but active cluster node not found"`

Same error can then be found when trying to inject our pods with the vault-webhooks and in the vault-configurer pod.
Injection seems to work after somehow long periods of time and at random.

It used to work fine on Kubernetes 1.23.5-gke.1501.

Injection seems to work, albeit at random.
The GCP Bucket  "bzcloud-vault-team" is still here, and the bzcloud-vault-team/core/leader file is here and is being updated at each reboot.

The only way to have a fully functionnal UI & Injection is to re size the Vault Ressource to 1.

**Expected behaviour**:
UI and Injection should still work with more than 1 vault server after switching to 1.23.5-gke.1503

**Steps to reproduce the bug**:
On a GKE cluster with K8S 1.23.5-gke.1503, deploy Banzaicloud Vault, and spec a size : 2 or more for the  vault.banzaicloud.com/v1alpha1 ressource.

**Environment details**:
- Kubernetes version :v1.23.5-gke.1503
- Cloud-provider/provisioner : GKE
- bank-vaults version : latest
- Install method : Using Flux + Helm chart for both operator & webhook, and a yaml definition for the Vault server ressource
- Logs from the misbehaving component :

On the Configurer : 
`{"level":"error","msg":"error configuring vault: error configuring auth methods for vault: error configuring managed auth methods: error while adding auth method config: error configuring kubernetes auth for vault: error putting kubernetes auth config into vault: Error making API request.\n\nURL: PUT http://vault-server-app.vault:8200/v1/auth/kubernetes/config\nCode: 500. Errors:\n\n* local node not active but active cluster node not found","time":"2022-07-05T12:39:46Z"}`

On the sidecar vault-env trying to inject : 
`time="2022-07-05T09:22:52Z" level=error msg="failed to request new Vault token" app=vault-secrets-webhook err="Error making API request.\n\nURL: PUT http://vault-server-app.vault:8200/v1/auth/kubernetes/login\nCode: 500. Errors:\n\n* local node not active but active cluster node not found"`

Sometimes, on the vault pod in Vault server : 
`Error flushing to statsd! Err: write udp 127.0.0.1:51127->127.0.0.1:9125: write: connection refused
`

- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault-operator
  namespace: vault
  annotations:
    flux.weave.works/ignore: 'false'
    helm.fluxcd.io/migrate: "true" 
    prometheus.io/scrape: "true"
    prometheus.io/port: "9125"
    prometheus.io/path: /metrics

spec:
  releaseName: vault-operator
  chart:
    repository: http://kubernetes-charts.banzaicloud.com/branch/master
    name: vault-operator
    version: 1.15.8
  values:
    image:

      pullPolicy: IfNotPresent
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    replicaCount: 1
    service:
      type: ClusterIP
      externalPort: 80
      internalPort: 8080
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    etcd-operator:
      enabled: false
    psp:
      enabled: false
    serviceAccount:
      create: true
      name: vault-serviceaccount
    tolerations:
    - key: "admin"
      operator: "Exists"
      effect: "NoExecute"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-delegator-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-serviceaccount
  namespace: vault
---
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:

  name: vault-server-app

  namespace: vault
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9102"
    prometheus.io/path: /metrics
spec:
  size: 1
  tolerations:
    - key: "admin"
      operator: "Exists"
      effect: "NoExecute"
  resources:
    vault:
      limits:
        cpu: 1
        memory: 1024Mi
      requests:
        cpu: 250m
        memory: 256Mi
    bankVaults:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi          

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key:  app.kubernetes.io/name
              operator: In
              values:
              - vault
          topologyKey: cloud.google.com/gke-nodepool
      - weight: 80
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key:  app.kubernetes.io/name
              operator: In
              values:
              - vault
          topologyKey:  topology.gke.io/zone                  

  serviceAccount: vault-serviceaccount


  unsealConfig:
    google:
      kmsKeyRing: "vault-team"
      kmsCryptoKey: "vault-team" 
      kmsLocation: "global" 
      kmsProject: "team-infra-preprod-ynck" 
      storageBucket: "bzcloud-vault-team" 
  config:
    # logLevel : debug
    seal:
      gcpckms:
        crypto_key: "vault-team" 
        key_ring: "vault-team"
        project: "team-infra-preprod-ynck" 
        region: global
    storage:
      gcs:
        bucket: "bzcloud-vault-team"
        ha_enabled: "true"
    listener:
       tcp: 
         address: "[::]:8200"
         tls_disable: true

    api_addr: http://vault-server-app.vault:8200
    ui: true
    telemetry:
      statsd_address: localhost:9125
      disable_hostname: true
  credentialsConfig:
    env: GOOGLE_APPLICATION_CREDENTIALS
    path: /etc/gcp/service-account.json
    secretName: gcp-vault-sa
  envsConfig:
  - name: CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: vault-oidc
        key: client_id
  - name: CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: vault-oidc
        key: client_secret
  externalConfig:
    auth:
    - roles:
      - name: default
        bound_service_account_names:
        - default
        - vault-secrets-webhook
        bound_service_account_namespaces:
        - default
        - vault
        policies: 
        - allow_secrets
        ttl: 1h

      type: kubernetes
    policies:
    - name: allow_secrets
      rules: path "secret/*" { capabilities = ["create", "read", "update", "delete", "list"] }

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: vault-bzcloud-ingress-nginx
   namespace: vault
   annotations:
     flux.weave.works/ignore: "false"
     kubernetes.io/ingress.class: "nginx"
spec:
   rules:
   - host: "vault-team.pp.dktapp.cloud"
     http:
       paths:
        - backend:
            service:
              name: vault-server-app
              port:
                number: 8200
          path: /
          pathType: ImplementationSpecific      
```

/kind bug

**Comment by AndreasSko** [comment]
We are facing the same issue as you described. Interestingly it seems to have started after upgrading Vault from v1.10.3 to v1.11.0. After a downgrade, the issue disappeared.

**Comment by gbuirel** [comment]
Tried to rollback up to Operator chart 1.11.1, still got the issue.

**Comment by AndreasSko** [comment]
@gbuirel what **Vault** image are you running? Is it possible that it's 1.11.0? If so, what happens if you explicitly pin it to an earlier version? 🤔

**Comment by DmitriyEsin** [comment]
Hi!
I confirm that rolling back to version 1.9.2 solved the problem. 
Cluster in HA mode, and I get no such errors anymore!

**Comment by jonwtech** [comment]
Encountered the same issue on k8s v1.20.11-aliyun.1 upgrading from Vault 1.9.2 -> 1.11.1. Downgrading to 1.10.5 resolves the issue.

**Comment by paul-yolabs** [comment]
Same on EKS 1.21 (with DynamoDB storage) with Vault 1.11.3.  Reverting to Vault 1.10.6 works.

Specifically, we saw the following behavior with vault status from the standby node:
```
  vault status
Key                    Value
---                    -----
Seal Type              shamir
Initialized            true
Sealed                 false
Total Shares           5
Threshold              3
Version                1.11.3
Storage Type           dynamodb
Cluster Name           vault-cluster-30143bed
Cluster ID             12669329-b727-3498-f403-bf495f8c2491
HA Enabled             true
HA Cluster             n/a
HA Mode                standby
Active Node Address    <none>
```

after revert, the API address is included as the active node address:
```
 vault status
Key                    Value
---                    -----
Seal Type              shamir
Initialized            true
Sealed                 false
Total Shares           5
Threshold              3
Version                1.10.6
Storage Type           dynamodb
Cluster Name           vault-cluster-30143bed
Cluster ID             12669329-b727-3498-f403-bf495f8c2491
HA Enabled             true
HA Cluster             https://vault.vault:8201
HA Mode                standby
Active Node Address    https://vault.vault:8200
```

snippet:
```
  config:
    api_addr: https://vault.vault:8200   
```

**Comment by karnphongkie** [comment]
I encountered the same issue when having version 1.10.6 and size is 3 when run the vault operator members out only have 2 members

**Comment by mkostelcev** [comment]
same for me

**Comment by ftpd** [comment]
I can confirm I had the same issue on versions 1.11.x, 1.12.0 and 1.12.1 on EKS 1.22.

**Comment by jonwtech** [comment]
I have yet to resolve this issue and am still stuck on 1.10. Yet elsewhere I have created a brand new 3 node cluster running 1.11.4 and it works perfectly. The main difference is that the new cluster is using the Raft storage backend, whereas the cluster I can't upgrade is using the PostgresQL storage backend. I wonder if this is significant given that the two people who have mentioned their storage configs on this thread are using GCS and DynamoDB.

Possibly this is an issue that only affects certain backends - I will have to try spinning up a new cluster with PostgreSQL backend or migrating the non-upgradable cluster to Raft to confirm.

**Comment by kirilvasilev** [comment]
I believe you have to set the `cluster_addr` field in the config like so:
```
  config:
    listener:
      tcp:
        address: "0.0.0.0:8200"
        cluster_address: "0.0.0.0:8201"
    api_addr: "https://${.Env.POD_IP}:8200"
    cluster_addr: "https://${.Env.POD_IP}:8201"
  vaultEnvsConfig:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
```
We're running Vault with DynamoDB backend in HA with 3 pods per cluster and multiple clusters per namespace. 
Vault 1.13.0
Bank Vaults Operator 1.19
Kubernetes 1.23
