### ISSUE TITLE
k8s auth and cert-manager with EKS v1.23 not working

### ISSUE THREAD

**Issue by suchitsancheti** [bank-vaults/bank-vaults#1699]
**Describe the bug**:
After enabling the k8s auth, the cert-manager issuer is failing with the permission denied error.

**Expected behaviour**:
Expected behaviour is that the cert-manager is setup correctly after enabling the k8s auth in the vault on EKS v1.23.

**Steps to reproduce the bug**:
1. Deploy the vault using vault.banzaicloud.com/v1alpha1 CRD as follows:
```
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
  namespace: "vault"
spec:
  size: 1
  image: hashicorp/vault:1.12.0
  externalConfig:
    policies:
      - name: k8s-ops
        rules:
          path "secret/data/ops/*" {
            capabilities = ["read", "list"]
          }

          path "vaultCA*" { 
            capabilities = ["read", "list"]
          }

          path "vaultCA/issue/cluster-local" { 
            capabilities = ["create"]
          }

          path "vaultCA/sign/cluster-local" {
            capabilities = ["create", "update"]
          } 
    auth:
      - type: kubernetes
         path: kubernetes/ops
         config:
           kubernetes_host: https://kubernetes.default.svc
           disable_local_ca_jwt: true
         roles:
           - name: k8s-ops
              bound_service_account_names: ["issuer"]
              bound_service_account_namespaces: ["cert-manager"]
              policies: ["k8s-ops", "default"]
              ttl: 5m   
```

2. Deploy the cert-manager v1.9.1 in cert-manager namespace. Create a serviceaccount `issuer` in `cert-manager` namespace.
3. Create a clusterrolebinding as `kubectl create clusterrolebinding vault-client-auth-delegator --clusterrole=system:auth-delegator --serviceaccount=cert-manager:issuer`
4. Create an issuer as follows:
```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: cert-manager
spec:
  vault:
    server: http://vault.vault:8200
    path: vaultCA/sign/cluster-local
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes/ops
        role: k8s-ops
        secretRef:
          name: issuer-token-f6dtr
          key: token
```
5. The error while describing the issuer is:

```
    Message:               Failed to initialize Vault client: error reading Kubernetes service account token from issuer-token-f6dtr: error calling Vault server: Error making API request.

URL: POST http://vault.vault:8200/v1/auth/kubernetes/ops/login
Code: 403. Errors:

* permission denied
    Observed Generation:  2
    Reason:               VaultError
    Status:               False
    Type:                 Ready
Events:
  Type     Reason         Age                From                  Message
  ----     ------         ----               ----                  -------
  Warning  ErrInitIssuer  7s (x2 over 8s)    cert-manager-issuers  Error initializing issuer: error reading Kubernetes service account token from issuer-token-f6dtr: error calling Vault server: Error making API request.

URL: POST http://vault.vault:8200/v1/auth/kubernetes/ops/login
Code: 403. Errors:

* permission denied
```

**Additional context**:
I am trying to configure vault as CA and use cert-manager as certificate issuer.

**Environment details**:
- Kubernetes version: v1.23
- Cloud-provider/provisioner: EKS
- bank-vaults version: 1.16.1
- Install method: helm
- Vault version: 1.12.0

/kind bug
