### ISSUE TITLE
purgeUnmanagedConfig does not purge secrets engines' configuration

### ISSUE THREAD

**Issue by aabdala** [bank-vaults/bank-vaults#1843]
When using for example the aws secrets engine, deleting configuration entries for that secrets engine when enabling `purgeUnmanagedConfig` does not seem to be deleting them from vault.

From what I've seen in [this code](https://github.com/banzaicloud/bank-vaults/blob/main/internal/vault/secrets_engines.go) it seems to me that either the whole secrets engine is removed if it is not present in the config, or it is left/tuned and existing and new configuration entries are upserted, but the diffing to remove the ones not present in the config anymore does not seem to be implemented.

As an example, having configured the following (trimmed down for brevity)
```yaml
  externalConfig:
    secrets:
    - description: AWS secret backend.
      path: aws/
      type: aws
      configuration:
        roles:
        - credential_type: assumed_role
          name: role-1
          role_arns:
          - arn:aws:iam::1234567890:role/role-1
        - credential_type: assumed_role
          name: role-2
          role_arns:
          - arn:aws:iam::1234567890:role/role-2
```

After deleting the item for `role-2` from the Vault CR configuration, a `vault read aws/roles/role-2` would still return successfully.

This was tested with bank-vaults version 1.15.8 and vault version 1.10.4

/kind bug
