### ISSUE TITLE
Unable to mount Kubernetes auth at a different mount point

### ISSUE THREAD

**Issue by patrickdappollonio** [bank-vaults/bank-vaults#1876]
Hello all! I tried to sign-up for Slack to discuss this there, but I was unable to do so (the form redirects to Slack "log-in" for which you need a `@cisco.com` e-mail).

**Describe the bug**:
We want to onboard several clusters to Vault using this config:

```yaml
auth:
  - type: kubernetes
    config:
      token_reviewer_jwt: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9....
      kubernetes_ca_cert: |
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----
      kubernetes_host: https://192.168.64.42:8443
```

I couldn't find in the documentation how to change the mount path though to allow multiple clusters to be added to the Vault instance. I _feel_ if I were to change the `auth.type`, it would probably break since otherwise it has no way to know how to set it up as Kubernetes, but I could be wrong!

**Expected behaviour**:
Having a way to implement multiple clusters to serve as a vault auth method on different mount points, similar to:

```bash
vault auth enable --path=dev-cluster kubernetes
vault write auth/dev-cluster/config \
    token_reviewer_jwt="<redacted>" \
    kubernetes_host=<redacted> \
    kubernetes_ca_cert="<redacted>" \
    issuer="https://kubernetes.dev-cluster.example.com"
    
vault auth enable --path=prod-cluster kubernetes
vault write auth/prod-cluster/config \
    token_reviewer_jwt="<redacted>" \
    kubernetes_host=<redacted> \
    kubernetes_ca_cert="<redacted>" \
    issuer="https://kubernetes.prod-cluster.example.com"
```

**Steps to reproduce the bug**:
N/A

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): N/A
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): N/A
- bank-vaults version (e.g. 0.4.17): 1.17.0
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs): N/A
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: N/A

/kind bug
