### ISSUE TITLE
Automating Intermediate CA Generation in Bank-Vaults

### ISSUE THREAD

**Issue by frnode** [bank-vaults/bank-vaults#3077]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/bank-vaults/issues) for an issue that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct).

## Add support for Intermediate CA with Root CA reference

Currently, bank-vaults supports root CA generation but lacks simple intermediate CA creation.

### Feature Request
Add support for intermediate CA generation with direct root CA reference.

### Example Configuration
```yaml
secrets:
  - type: pki
    path: pki
    configuration:
      root/generate:
        - name: internal
          common_name: "Root CA"
          ttl: 87600h
          key_type: rsa
          key_bits: 4096
  - type: pki
    path: pki_int
    configuration:
      intermediate/generate:
        - name: internal
          common_name: "Intermediate CA"
          ttl: 43800h
          signed_by: "pki/internal"  # Reference to root CA
```

### Implementation Details
- Add `signed_by` field to reference root CAs
- Format: `<path>/<name>`
- Automatic CSR generation and signing
- Support standard Vault PKI parameters

### Documentation
- Update configuration reference
- Add examples for different use cases

### Additional Information

https://github.com/orgs/bank-vaults/discussions/3076
