### ISSUE TITLE
v1.31.3 fails to configure a cluster fully

### ISSUE THREAD

**Issue by dhumphries-sainsburys** [bank-vaults/bank-vaults#3227]
### Preflight Checklist

- [x] I have searched the [issue tracker](https://www.github.com/bank-vaults/bank-vaults/issues) for an issue that matches the one I want to file, without success.
- [x] I am not looking for support or already pursued the available [support channels](https://bank-vaults.dev/docs/support) without success.
- [x] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct).

### Version

v1.31.3

### Expected Behavior

vault-configurer configures new auth endpoints & can properly setup a new cluster

### Actual Behavior

We had configured 2 new auth for a new k8s cluster like so ....

```
      - config:
          disable_iss_validation: true
          disable_local_ca_jwt: true
          kubernetes_ca_cert: |
            ...
          kubernetes_host: >-
            https://.....eu-west-1.eks.amazonaws.com
          token_reviewer_jwt: >-
            ...
        path: kubernetes-test-3
        roles:
          - bound_service_account_names:
              - '*'
            bound_service_account_namespaces:
              - vault-operator
            name: vault-operator
            policies:
              - admin
            ttl: 1h
          - bound_service_account_names:
              - '*'
            bound_service_account_namespaces:
              - actions-runner
            name: actions-runner
            policies:
              - actions-runner
            ttl: 1h
          - bound_service_account_names:
              - build
              - deploy
              - basic
            bound_service_account_namespaces:
              - '*'
            name: shared-slack
            policies:
              - shared-slack
            ttl: 1h
        type: kubernetes
      - config:
          bound_issuer: >-
            https://oidc.eks.eu-west-1.amazonaws.com/id/...
          oidc_discovery_url: >-
            https://oidc.eks.eu-west-1.amazonaws.com/id/...
        path: jwt-kubernetes-test-3
        roles:
          - bound_audiences: vault
            name: vault-operator
            policies: admin
            role_type: jwt
            ttl: 1h
            user_claim: sub
          - bound_audiences: vault
            name: vault-all-service-accounts
            policies: headlamp_read
            role_type: jwt
            ttl: 1h
            user_claim: sub
          - bound_audiences: vault
            name: actions-runner
            policies: actions-runner
            role_type: jwt
            ttl: 1h
            user_claim: sub
          - bound_audiences: vault
            bound_claims:
              /kubernetes.io/serviceaccount/name:
                - build
                - basic
                - deploy
            name: shared-slack
            policies: shared-slack
            role_type: jwt
            token_ttl: 1h
            user_claim: sub
        type: jwt
```
I noticed that the new authentication methods weren't being configured. Logs for vault, configurer and operator show no problems. This lead me to try creating a new vault with both this config and the previously working one on a blank s3 bucket. This time around i see that it correctly setup 2 out of the 6 auth endpoints but also other parts of the config weren't being configured correctly as well such as anything allowing me to login.

### Steps To Reproduce

1. Deploy vault-operator (v1.22.5)
2. Construct vault CR (bank-vaults: v1.31.3 & vault: 1.18.3)
3. Add new auth config

Alternatively

1. Deploy vault-operator (v1.22.5)
2. Construct vault CR (bank-vaults: v1.31.3 & vault: 1.18.3) with several auth endpoints

### Logs

```shell
None really helpful
```

### Additional Information

Going back to v1.31.2 seems to solve the problem
