### ISSUE TITLE
[operator] retry if unseal secret is not created

### ISSUE THREAD

**Issue by rjbez17** [bank-vaults/bank-vaults#591]
**Describe the bug**:
During our deployment of a vault resource using kubernetes secrets for unseal keys, we've seen an instance of the unseal secret not being created. Our api service had some contention at this point, and my best guess is the call to create the secret failed. However, the operator didn't attempt to retry.

I attempted to delete the vault CR and redeploy and it didn't recreate the unseal keys (likely because they were created and saved in etcd and no long accessible). After deleting and recreating both the etcd cluster and vault CR it successfully created the secret without issue (and therefore unseal vault).

**Expected behaviour**:
The operator will continue to attempt to create the unseal secret if errors occur.

**Steps to reproduce the bug**:
Unknown, best guess would be to have an overloaded api server (like doing a bunch of helm installs asynchronously) while the vault resource is being created. Note we've only seen this once in over a hundred deploys (CI test systems).

**Additional context**:
Bare metal install using the official helm chart to deploy the operator. We are also using an etcd operator to deploy the cluster separately from vault.

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.14.3
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): N/A (bare metal)
- bank-vaults version (e.g. 0.4.17): 0.4.16
- Install method (e.g. helm or static manifests): helm for operator, separate chart for vault custom resource
- Logs from the misbehaving component (and any other relevant logs):

The operator didn't have much other than this:

```
W0808 01:14:32.619073       1 reflector.go:270] pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20181213151034-8d9ed539ba31+incompatible/tools/cache/reflector.go:95: watch of *v1.Pod ended with: too old resource version: 36864 (38712)
```

The `bank-vaults` sidecar had this:

```
time="2019-08-08T01:36:27Z" level=info msg="vault is sealed, unsealing"
time="2019-08-08T01:36:27Z" level=error msg="error unsealing vault: unable to get key 'vault-unseal-0': error getting secret for key 'vault-unseal-0': secrets \"vault-unseal-keys\" not found"
```

- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

```
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  namespace: vault
spec:
  annotations: {}
  bankVaultsImage: private-dtr.foo:5000/banzaicloud/bank-vaults:0.4.16
  config:
    api_addr: http://vault.vault:8200
    listener:
      tcp:
        address: 0.0.0.0:8200
        tls_disable: true
    storage:
      etcd:
        address: http://vault-etcd-client:2379
        ha_enabled: "true"
        sync: "false"
    ui: false
  credentialsConfig:
    env: ""
    path: ""
    secretName: ""
  envsConfig: null
  etcdSize: -1
  etcdVersion: ""
  externalConfig:
    auth:
    - roles:
      - bound_service_account_names: '*'
        bound_service_account_namespaces: services
        name: services
        policies: allow_secrets
        ttl: 72h
      type: kubernetes
    policies:
    - name: allow_secrets
      rules: path "secret/*" { capabilities = ["create", "read", "update", "delete",
        "list"] }
    secrets:
    - description: General secrets.
      options:
        version: 2
      path: secret
      type: kv
  fluentdConfig: ""
  fluentdEnabled: false
  fluentdImage: ""
  image: private-dtr.foo:5000/library/vault:1.1.2
  nodeAffinity: {}
  nodeSelector: null
  podAntiAffinity: ""
  securityContext: {}
  serviceAccount: vault
  servicePorts: null
  serviceType: ""
  size: 1
  statsdDisabled: false
  statsdImage: private-dtr.foo:5000/prom/statsd-exporter:v0.10.5
  tolerations: null
  unsealConfig:
    kubernetes:
      secretName: ""
      secretNamespace: vault
    options: {}
  vaultAnnotations: {}
  vaultConfigurerAnnotations: {}
  vaultEnvsConfig: null
  watchedSecretsLabels: []
```

/kind bug
