### ISSUE TITLE
[vswh:chart] pre-requisite/behavior clarification

### ISSUE THREAD

**Issue by tony-kerz** [bank-vaults/bank-vaults#970]
**Is your feature request related to a problem? Please describe.**

the [documentation](https://github.com/banzaicloud/bank-vaults/tree/master/charts/vault-secrets-webhook#using-external-vault-instances) implies that a cluster-role-binding like the following must be applied by the person doing the installation:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: vault-tokenreview-binding
  namespace: vswh # Change it if you don't use the defaults when you install it via Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vswh-vault-secrets-webhook # Change it if you don't use the defaults when you install it via Helm
  namespace: vswh # Change it if you don't use the defaults when you install it via Helm
```

i "inherited" an installation performed by another individual where there was no such crb,
but instead a crb installed in each namespace like the following:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-ns-role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: default
  namespace: my-ns
```

based on what i inherited, and the fact that the documentation didn't really provide detail around this crb, i assumed that in order to isolate secret-access to a namespace, a distinct crb in each namespace was required.

a little bit later (now), i'm using the latest version of the chart (`1.2.0`) and having a little time to explore (but not too much 😄), i installed the chart __without__ providing any crb "manually" myself (neither in the vswh namespace or in any of the individual namespaces that are supposed to have an isolated set of vault-secrets), and to my surprise...

my pod running in my "secret-isolated" namespace was able to access it's secret successfully!

> based on the documentation and the strategy of the guy who installed before me, i expected this not to work

**Describe the solution you'd like**

some clarification on the behavior of the latest version (`v1.2.0`), especially when the desired effect is to isolate namespaces from each others secrets (think each namespace has it's own kv instance in vault).

**Describe alternatives you've considered**

?

**Additional context**

issue #929 could be somewhat related
